[platformio]
default_envs = f411_recovery_boot

[env:f411_recovery_boot]
platform = ststm32
board = blackpill_f411ce
framework = stm32cube
upload_protocol = stlink
board_upload.maximum_size = 32768
build_flags =
    -DAPP_BASE=0x08008000UL
    -DAPP_LIMIT=0x08060000UL
    -DMANIFEST_ADDR=0x08060000UL
    -DSYSTEM_MEMORY=0x1FFF0000UL
    -DBOOT_REQUEST_MAGIC=0x42465544UL
