'use strict';
// ================= TUNING & CONTROL WORKBENCH V3 =================
let selectedExperiment=null, selectedTableIndex=0, selectedGraphIndex=0;
const metricHistory=new Map(), scatterHistory=new Map(), tableRunRows=new Map(), localRunValues={};
let recordStartedMs=0, recordUiTimer=null, lastLabSecond=-1, lastLabTelemetryTick=-1, recordingLeafId='', recordingDomain='', recordingRunToken='';
let reportEvidenceFrozen=false, reportEvidenceFrozenLeaf='', reportSourceTableRenderMs=0;
const reportPathSnapshots=new Map();
let trialStore={version:1},commissioningState={qualifications:{},phase:{}},trialMotionTimer=null,trialMotionActive=false,trialMotionErpm=0,lastTrialArtifacts=null;const trialCompareSelection=new Set();
const LAB_COLORS=['#48e0a4','#55b8ff','#ffc86b','#bd8cff','#ff7b8a','#54d6e8','#9ce36b'];
const F=(label,file,path,kind='float',readOnly=false,help='')=>({label,yamlFileKey:file,yamlPath:path,kind:readOnly?'yaml_readonly':kind,help});
const WEB_TUNING={
  perception:{
    '4.1.1':[F('Inference CPU target FPS','perception','perception.ros__parameters.cpu_inference_fps'),F('CPU threads','perception','perception.ros__parameters.cpu_threads','int'),F('Camera FPS','perception','perception.ros__parameters.fps','int',true)],
    '4.1.2':[F('RGB width','perception','perception.ros__parameters.rgb_width','int'),F('RGB height','perception','perception.ros__parameters.rgb_height','int'),F('Camera FPS','perception','perception.ros__parameters.fps','int'),F('Strict camera mode','perception','perception.ros__parameters.strict_camera_mode','bool'),F('V4L2 buffer count','perception','perception.ros__parameters.v4l2_buffer_count','int')],
    '4.1.3':[F('Pixel format','perception','perception.ros__parameters.v4l2_pixel_format','string'),F('Allow MJPEG CPU fallback','perception','perception.ros__parameters.allow_mjpeg_cpu_fallback','bool'),F('Flip horizontal','perception','perception.ros__parameters.flip_horizontal','bool')],
    '4.1.4':[F('RViz max publish rate','perception','perception.ros__parameters.rviz_max_publish_rate_hz'),F('Web preview enabled','perception','perception.ros__parameters.web_preview_enabled','bool'),F('Web preview FPS','perception','perception.ros__parameters.web_preview_fps'),F('Web preview width','perception','perception.ros__parameters.web_preview_width','int'),F('Web preview height','perception','perception.ros__parameters.web_preview_height','int'),F('Web preview JPEG quality','perception','perception.ros__parameters.web_preview_jpeg_quality','int'),F('Publish annotated','perception','perception.ros__parameters.publish_annotated','bool'),F('Publish raw RGB','perception','perception.ros__parameters.publish_raw_rgb','bool'),F('Async RViz publish','perception','perception.ros__parameters.async_rviz_publish','bool')],
    '4.2.1':[F('Minimum obstacle confidence','perception','perception.ros__parameters.minimum_obstacle_confidence'),F('Raw confidence threshold','perception','perception.ros__parameters.confidence_threshold'),F('NMS IoU threshold','perception','perception.ros__parameters.iou_threshold'),F('Accept all classes as safety obstacle','perception','perception.ros__parameters.accept_all_detected_classes_as_obstacles','bool'),F('Safety class IDs (person,car,motorcycle)','perception','perception.ros__parameters.safety_obstacle_class_ids','list',false,'Final safety mapping: [0,2,3]. Raw class lain tetap dapat tampil untuk debug.')],
    '4.2.2':[F('Require drivable contact','perception','perception.ros__parameters.require_drivable_contact','bool'),F('Contact radius px','perception','perception.ros__parameters.drivable_contact_radius_px','int'),F('Contact vertical tolerance px','perception','perception.ros__parameters.drivable_contact_vertical_tolerance_px','int'),F('Contact min samples','perception','perception.ros__parameters.drivable_contact_min_samples','int'),F('Contact min fraction','perception','perception.ros__parameters.drivable_contact_min_fraction')],
    '4.2.3':[F('Track confirm hits','perception','perception.ros__parameters.track_confirm_hits','int'),F('Blocked confirm frames','perception','perception.ros__parameters.blocked_confirm_frames','int'),F('Clear confirm frames','perception','perception.ros__parameters.clear_confirm_frames','int')],
    '4.2.4':[F('Track max missed frames','perception','perception.ros__parameters.track_max_missed_frames','int'),F('Track match distance m','perception','perception.ros__parameters.track_match_distance_m'),F('Clearing obstacle margin m','perception','perception.ros__parameters.clearing_obstacle_margin_m')],
    '4.2.5':[F('Minimum obstacle confidence','perception','perception.ros__parameters.minimum_obstacle_confidence', 'float',true),F('Metric maximum forward m','perception','perception.ros__parameters.metric_maximum_forward_m','float',true)],
    '4.3.1':[F('Calibration width','perception','perception.ros__parameters.ground_calibration_width','int'),F('Calibration height','perception','perception.ros__parameters.ground_calibration_height','int'),F('Ground source points [x1,y1,...]','perception','perception.ros__parameters.ground_src_points','list'),F('Ground destination points [x1,y1,...]','perception','perception.ros__parameters.ground_dst_points','list'),F('Ground origin X px','perception','perception.ros__parameters.ground_origin_x_px'),F('Ground origin Y px','perception','perception.ros__parameters.ground_origin_y_px'),F('Meters/pixel X','perception','perception.ros__parameters.ground_meters_per_pixel_x'),F('Meters/pixel Y','perception','perception.ros__parameters.ground_meters_per_pixel_y')],
    '4.3.2':[F('Metric min forward m','perception','perception.ros__parameters.metric_minimum_forward_m'),F('Metric max forward m','perception','perception.ros__parameters.metric_maximum_forward_m'),F('Metric max abs lateral m','perception','perception.ros__parameters.metric_maximum_abs_left_m'),F('Calibration validated','perception','perception.ros__parameters.camera_metric_calibration_validated','bool',true)],
    '4.3.3':[F('Forward offset m','perception','perception.ros__parameters.metric_forward_offset_m'),F('Lateral offset m','perception','perception.ros__parameters.metric_lateral_offset_m')],
    '4.3.4':[F('Track EMA alpha','perception','perception.ros__parameters.track_ema_alpha'),F('Track match distance m','perception','perception.ros__parameters.track_match_distance_m'),F('Track max missed frames','perception','perception.ros__parameters.track_max_missed_frames','int')],
    // 4.3.5 is an offline comparison experiment. Do not expose the legacy
    // bbox_obstacle_calibration.yaml as if it were consumed by the runtime node.
    '4.3.5':[],
    '4.4.1':[F('Drivable sample rows','perception','perception.ros__parameters.drivable_space_sample_rows','int'),F('Min pixels per row','perception','perception.ros__parameters.drivable_space_min_pixels_per_row','int'),F('Pixel stride','perception','perception.ros__parameters.drivable_space_pixel_stride_px','int')],
    '4.4.2':[F('Drivable near m','perception','perception.ros__parameters.drivable_space_near_m'),F('Drivable far m','perception','perception.ros__parameters.drivable_space_far_m'),F('Drivable max abs lateral m','perception','perception.ros__parameters.drivable_space_max_abs_left_m')],
    '4.5.1':[F('Lane threshold','perception','perception.ros__parameters.lane_threshold'),F('Nominal road width m','perception','perception.ros__parameters.nominal_road_width_m'),F('Vehicle width m','perception','perception.ros__parameters.lane_vehicle_width_m'),F('Minimum road width m','perception','perception.ros__parameters.lane_minimum_road_width_m'),F('Maximum road width m','perception','perception.ros__parameters.lane_maximum_road_width_m'),F('Minimum metric confidence','perception','perception.ros__parameters.minimum_metric_confidence')],
    '4.5.2':[F('Lane EMA alpha','perception','perception.ros__parameters.lane_ema_alpha'),F('Control lookahead m','perception','perception.ros__parameters.lane_control_lookahead_m'),F('Center gain','perception','perception.ros__parameters.center_gain'),F('Heading gain','perception','perception.ros__parameters.heading_gain'),F('Safety line top Y ratio','perception','perception.ros__parameters.lane_corridor_top_y_ratio'),F('Safety line bottom Y ratio','perception','perception.ros__parameters.lane_corridor_bottom_y_ratio'),F('Camera height m (URDF 0.736)','perception','perception.ros__parameters.lane_corridor_camera_height_m'),F('Camera pitch deg','perception','perception.ros__parameters.lane_corridor_camera_pitch_deg'),F('Safety margin each side m','perception','perception.ros__parameters.lane_corridor_safety_margin_m'),F('Far lookahead m (top width)','perception','perception.ros__parameters.lane_corridor_far_lookahead_m'),F('Pair center shift px','perception','perception.ros__parameters.lane_corridor_center_offset_px'),F('Left line shift px','perception','perception.ros__parameters.lane_corridor_left_offset_px'),F('Right line shift px','perception','perception.ros__parameters.lane_corridor_right_offset_px')],
    '4.5.3':[F('Edge warning clearance m','perception','perception.ros__parameters.edge_warning_clearance_m'),F('Edge critical clearance m','perception','perception.ros__parameters.edge_critical_clearance_m'),F('Edge release clearance m','perception','perception.ros__parameters.edge_release_clearance_m'),F('State confirm frames','perception','perception.ros__parameters.state_confirm_frames','int'),F('Release confirm frames','perception','perception.ros__parameters.release_confirm_frames','int'),F('Lost confirm frames','perception','perception.ros__parameters.lost_confirm_frames','int'),F('Safety-line warning gap px','perception','perception.ros__parameters.lane_corridor_warning_gap_px'),F('Safety-line touch margin px','perception','perception.ros__parameters.lane_corridor_touch_margin_px'),F('Critical penetration px','perception','perception.ros__parameters.lane_corridor_critical_penetration_px'),F('Corridor min valid rows','perception','perception.ros__parameters.lane_corridor_minimum_valid_rows','int')],
    '4.5.4':[F('Center deadband m','perception','perception.ros__parameters.center_deadband_m'),F('Lane lookahead near m','perception','perception.ros__parameters.lane_lookahead_near_m'),F('Lane lookahead far m','perception','perception.ros__parameters.lane_lookahead_far_m'),F('Lane min valid rows','perception','perception.ros__parameters.lane_minimum_valid_rows','int'),F('Corridor min drivable fraction','perception','perception.ros__parameters.lane_corridor_minimum_drivable_fraction','float'),F('Corridor correction gain m/px','perception','perception.ros__parameters.lane_corridor_correction_gain_m_per_px'),F('Corridor max correction m','perception','perception.ros__parameters.lane_corridor_max_correction_m')],
    '4.6.1':[F('Dark luma','perception','perception.ros__parameters.camera_health_dark_luma','int'),F('Bright luma','perception','perception.ros__parameters.camera_health_bright_luma','int'),F('Extreme fraction','perception','perception.ros__parameters.camera_health_extreme_fraction'),F('Min stddev','perception','perception.ros__parameters.camera_health_min_stddev'),F('Min gradient','perception','perception.ros__parameters.camera_health_min_gradient'),F('Bad confirm frames','perception','perception.ros__parameters.camera_health_bad_confirm_frames','int'),F('Good confirm frames','perception','perception.ros__parameters.camera_health_good_confirm_frames','int')],
    '4.6.2':[F('Near-field min confidence','perception','perception.ros__parameters.near_field_min_confidence'),F('Center corridor fraction','perception','perception.ros__parameters.near_field_center_corridor_fraction'),F('Min bbox height fraction','perception','perception.ros__parameters.near_field_min_bbox_height_fraction'),F('Bottom ROI fraction','perception','perception.ros__parameters.near_field_bottom_roi_fraction'),F('Drivable guard enabled','perception','perception.ros__parameters.near_field_drivable_guard_enabled','bool'),F('Min drivable fraction','perception','perception.ros__parameters.near_field_min_drivable_fraction'),F('Confirm frames','perception','perception.ros__parameters.near_field_confirm_frames','int'),F('Release frames','perception','perception.ros__parameters.near_field_release_frames','int')],
    '4.7.1':[F('Trajectory lateral margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.trajectory_lateral_margin_m'),F('Path horizon m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.path_horizon_m'),F('Obstacle timeout s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.obstacle_timeout_sec'),F('Plan timeout s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.plan_timeout_sec')],
    '4.7.2':[F('Planning lateral margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.planning_lateral_margin_m'),F('Planning min forward m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.planning_min_forward_m'),F('Planning max abs lateral m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.planning_max_abs_lateral_m'),F('Require plan when moving','trajectory_safety','trajectory_safety_supervisor.ros__parameters.require_plan_when_moving','bool')],
    '4.7.3':[F('Slow path distance m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.slow_path_distance_m'),F('Minimum slow speed scale','trajectory_safety','trajectory_safety_supervisor.ros__parameters.minimum_slow_speed_scale'),F('Warning lane speed m/s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.warning_lane_speed_mps'),F('Lane timeout s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.lane_timeout_sec'),F('Drivable timeout s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.drivable_timeout_sec')],
    '4.7.4':[F('Hard stop path distance m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.hard_stop_path_distance_m'),F('Immediate hard stop m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.immediate_command_hard_stop_m'),F('Command collision horizon m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.command_collision_horizon_m'),F('Collision lateral margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.command_collision_lateral_margin_m'),F('Latency compensation','trajectory_safety','trajectory_safety_supervisor.ros__parameters.latency_compensation_enabled','bool'),F('Latency fallback s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.perception_latency_fallback_sec'),F('Latency safety margin s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.latency_safety_margin_sec'),F('Distance safety margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.latency_distance_margin_m'),F('Braking decel m/s²','trajectory_safety','trajectory_safety_supervisor.ros__parameters.braking_deceleration_mps2'),F('Max dynamic stop m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.max_dynamic_stop_distance_m'),F('Nav command timeout s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.nav_cmd_timeout_sec'),F('Advisory timeout s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.advisory_timeout_sec')],
    '4.7.5':[F('Avoidance speed m/s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.avoidance_speed_mps'),F('Avoidance side margin m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.avoidance_side_margin_m'),F('Boundary lookup tolerance m','trajectory_safety','trajectory_safety_supervisor.ros__parameters.avoidance_boundary_lookup_tolerance_m'),F('Critical lane speed m/s','trajectory_safety','trajectory_safety_supervisor.ros__parameters.critical_lane_speed_mps'),F('Require drivable for avoidance','trajectory_safety','trajectory_safety_supervisor.ros__parameters.require_drivable_space_for_avoidance','bool'),F('Require camera connected','trajectory_safety','trajectory_safety_supervisor.ros__parameters.require_camera_connected','bool'),F('Require camera health','trajectory_safety','trajectory_safety_supervisor.ros__parameters.require_camera_health','bool'),F('Require obstacle stream moving','trajectory_safety','trajectory_safety_supervisor.ros__parameters.require_obstacle_stream_when_moving','bool'),F('Stop on lane lost','trajectory_safety','trajectory_safety_supervisor.ros__parameters.stop_on_lane_lost','bool')],
    '4.8.1':[F('CPU inference FPS','perception','perception.ros__parameters.cpu_inference_fps'),F('Torch CPU threads','perception','perception.ros__parameters.cpu_threads','int'),F('OpenCV threads','perception','perception.ros__parameters.opencv_threads','int'),F('Torch optimize inference','perception','perception.ros__parameters.torch_optimize_for_inference','bool'),F('RViz publish max Hz','perception','perception.ros__parameters.rviz_max_publish_rate_hz'),F('Obstacle cloud max Hz','perception','perception.ros__parameters.obstacle_cloud_max_publish_rate_hz')],
    '4.9':[F('Metric calibration valid','perception','perception.ros__parameters.camera_metric_calibration_validated','bool',true),F('Lane safety enabled','perception','perception.ros__parameters.lane_safety_enabled','bool',true),F('Near-field enabled','perception','perception.ros__parameters.near_field_emergency_enabled','bool',true),F('Safety classes','perception','perception.ros__parameters.safety_obstacle_class_ids','list',true),F('Obstacle max forward m','perception','perception.ros__parameters.obstacle_forward_max_m','float',true)],
    '4.10':[F('Confidence threshold','perception','perception.ros__parameters.confidence_threshold','float',true),F('Obstacle confidence','perception','perception.ros__parameters.minimum_obstacle_confidence','float',true),F('Lane threshold','perception','perception.ros__parameters.lane_threshold','float',true),F('Track EMA','perception','perception.ros__parameters.track_ema_alpha','float',true)],
    '4.11':[]
  },
  steering:{
    '4.1':[F('PWM frequency Hz','foc_thesis','foc_thesis.runtime.pwm_frequency_hz','int',true),F('Telemetry rate Hz','foc_thesis','foc_thesis.runtime.telemetry_rate_hz','int'),F('Command timeout ms','foc_thesis','foc_thesis.runtime.command_timeout_ms','int'),F('Wheelbase m','esc','esc_ackermann.ros__parameters.wheelbase_m'),F('Track width m','esc','esc_ackermann.ros__parameters.track_width_m'),F('LEFT encoder PPR','foc_thesis','foc_thesis.encoder_mechanical.ppr','int',true),F('RIGHT pole pairs','esc','esc_ackermann.ros__parameters.drive_motor_pole_pairs','int',true),F('RIGHT gear ratio','esc','esc_ackermann.ros__parameters.drive_gear_ratio','float',true)],
    '4.2.1':[F('LEFT persistence','foc_thesis','foc_thesis.vesc_runtime_mirror.left.last_persistence','string',true),F('RIGHT persistence','foc_thesis','foc_thesis.vesc_runtime_mirror.right.last_persistence','string',true),F('LEFT max duty','foc_thesis','foc_thesis.vesc_runtime_mirror.left.max_duty','float',true),F('RIGHT max duty','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_duty','float',true)],
    '4.2.2':[F('Calibration sample count','foc_thesis','foc_thesis.current_vbus_calibration.sample_count','int'),F('Ia offset ADC','foc_thesis','foc_thesis.current_vbus_calibration.ia_offset_adc'),F('Ib offset ADC','foc_thesis','foc_thesis.current_vbus_calibration.ib_offset_adc'),F('Current gain A/count','foc_thesis','foc_thesis.current_vbus_calibration.current_gain_a_per_count'),F('Vbus scale V/count','foc_thesis','foc_thesis.current_vbus_calibration.vbus_scale_v_per_count')],
    '4.2.3':[F('Encoder PPR','foc_thesis','foc_thesis.encoder_mechanical.ppr','int',true),F('Encoder CPR','foc_thesis','foc_thesis.encoder_mechanical.cpr','int',true),F('Encoder direction','foc_thesis','foc_thesis.encoder_mechanical.direction','string'),F('Center count','foc_thesis','foc_thesis.encoder_mechanical.center_count','int'),F('Soft left limit deg','foc_thesis','foc_thesis.encoder_mechanical.soft_limit_left_deg'),F('Soft right limit deg','foc_thesis','foc_thesis.encoder_mechanical.soft_limit_right_deg'),F('LEFT position min count','foc_thesis','foc_thesis.vesc_runtime_mirror.left.position_min_counts','int',true),F('LEFT position max count','foc_thesis','foc_thesis.vesc_runtime_mirror.left.position_max_counts','int',true)],
    '4.2.4':[F('Phase order','foc_thesis','foc_thesis.electrical_alignment.phase_order','string'),F('LEFT pole pairs','foc_thesis','foc_thesis.electrical_alignment.pole_pairs','int',true),F('Theta offset rad','foc_thesis','foc_thesis.electrical_alignment.theta_offset_rad'),F('Alignment Iq A','foc_thesis','foc_thesis.electrical_alignment.alignment_iq_a'),F('Sector count','foc_thesis','foc_thesis.electrical_alignment.sector_count','int',true)],
    '4.2.5':[F('RIGHT pole pairs','esc','esc_ackermann.ros__parameters.drive_motor_pole_pairs','int',true),F('RIGHT gear ratio','esc','esc_ackermann.ros__parameters.drive_gear_ratio','float',true),F('RIGHT min eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.min_erpm'),F('RIGHT max eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_erpm'),F('RIGHT max duty','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_duty')],
    '4.3.1':[F('LEFT FOC Q Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.left.foc_q_kp'),F('LEFT FOC Q Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.left.foc_q_ki'),F('LEFT FOC D Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.left.foc_d_kp'),F('LEFT FOC D Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.left.foc_d_ki'),F('LEFT current filter','foc_thesis','foc_thesis.vesc_runtime_mirror.left.current_filter')],
    '4.3.2':[F('RIGHT FOC Q Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.right.foc_q_kp'),F('RIGHT FOC Q Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.right.foc_q_ki'),F('RIGHT FOC D Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.right.foc_d_kp'),F('RIGHT FOC D Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.right.foc_d_ki'),F('RIGHT current filter','foc_thesis','foc_thesis.vesc_runtime_mirror.right.current_filter')],
    '4.4.1':[F('LEFT Position Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.left.pos_kp'),F('LEFT Position Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.left.pos_ki'),F('LEFT Position Kd','foc_thesis','foc_thesis.vesc_runtime_mirror.left.pos_kd'),F('LEFT current filter','foc_thesis','foc_thesis.vesc_runtime_mirror.left.current_filter'),F('Operational steering limit deg','esc','esc_ackermann.ros__parameters.steering_physical_operational_limit_deg','float',true)],
    '4.4.2':[F('RIGHT Speed Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.right.speed_kp'),F('RIGHT Speed Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.right.speed_ki'),F('RIGHT Speed Kd','foc_thesis','foc_thesis.vesc_runtime_mirror.right.speed_kd'),F('RIGHT min eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.min_erpm'),F('RIGHT max eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_erpm')],
    '4.5.1':[F('Runs per direction','foc_thesis','foc_thesis.step_test.runs_per_direction','int'),F('Baseline hold s','foc_thesis','foc_thesis.step_test.baseline_hold_s'),F('Settling hold s','foc_thesis','foc_thesis.step_test.settling_hold_s'),F('Operational steering limit deg','esc','esc_ackermann.ros__parameters.steering_physical_operational_limit_deg','float',true)],
    '4.5.2':[F('RIGHT max duty','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_duty'),F('RIGHT input current max','foc_thesis','foc_thesis.vesc_runtime_mirror.right.input_current_max'),F('RIGHT max eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_erpm'),F('Baseline hold s','foc_thesis','foc_thesis.step_test.baseline_hold_s'),F('Settling hold s','foc_thesis','foc_thesis.step_test.settling_hold_s')],
    '4.6.1':[F('Physical left limit deg','esc','esc_ackermann.ros__parameters.steering_physical_left_limit_deg','float',true),F('Physical right limit deg','esc','esc_ackermann.ros__parameters.steering_physical_right_limit_deg','float',true),F('Operational limit deg','esc','esc_ackermann.ros__parameters.steering_physical_operational_limit_deg','float',true)],
    '4.6.2':[F('Runs per direction','foc_thesis','foc_thesis.step_test.runs_per_direction','int'),F('Steering LUT deadband deg','esc','esc_ackermann.ros__parameters.steering_lut_direction_deadband_deg')],
    '4.6.3':[F('Wheelbase m','esc','esc_ackermann.ros__parameters.wheelbase_m','float',true),F('Track width m','esc','esc_ackermann.ros__parameters.track_width_m','float',true),F('Inner wheel measured deg','foc_thesis','foc_thesis.step_test.measured_inner_wheel_deg'),F('Outer wheel measured deg','foc_thesis','foc_thesis.step_test.measured_outer_wheel_deg'),F('RIGHT gear ratio','esc','esc_ackermann.ros__parameters.drive_gear_ratio','float',true)],
    '4.7.1':[F('Steering sinus amplitude deg','foc_thesis','foc_thesis.tracking_test.amplitude_deg'),F('Frequency 0','foc_thesis','foc_thesis.tracking_test.frequencies_hz.0'),F('Frequency 1','foc_thesis','foc_thesis.tracking_test.frequencies_hz.1'),F('Frequency 2','foc_thesis','foc_thesis.tracking_test.frequencies_hz.2')],
    '4.7.2':[F('RIGHT Speed Kp','foc_thesis','foc_thesis.vesc_runtime_mirror.right.speed_kp','float',true),F('RIGHT Speed Ki','foc_thesis','foc_thesis.vesc_runtime_mirror.right.speed_ki','float',true),F('RIGHT Speed Kd','foc_thesis','foc_thesis.vesc_runtime_mirror.right.speed_kd','float',true),F('RIGHT max eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_erpm')],
    '4.8.1':[F('Load target deg','foc_thesis','foc_thesis.load_test.target_deg'),F('Selected load','foc_thesis','foc_thesis.load_test.selected_level','string'),F('LEFT max duty','foc_thesis','foc_thesis.vesc_runtime_mirror.left.max_duty','float',true)],
    '4.8.2':[F('Selected load','foc_thesis','foc_thesis.load_test.selected_level','string'),F('RIGHT input current max','foc_thesis','foc_thesis.vesc_runtime_mirror.right.input_current_max','float',true),F('RIGHT max duty','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_duty','float',true),F('RIGHT max eRPM','foc_thesis','foc_thesis.vesc_runtime_mirror.right.max_erpm','float',true)],
    '4.9':[F('Overcurrent A','foc_thesis','foc_thesis.safety_limits.overcurrent_a'),F('Undervoltage V','foc_thesis','foc_thesis.safety_limits.undervoltage_v'),F('Overvoltage V','foc_thesis','foc_thesis.safety_limits.overvoltage_v'),F('Overtemperature C','foc_thesis','foc_thesis.safety_limits.overtemperature_c'),F('LEFT persistence','foc_thesis','foc_thesis.vesc_runtime_mirror.left.last_persistence','string',true),F('RIGHT persistence','foc_thesis','foc_thesis.vesc_runtime_mirror.right.last_persistence','string',true)],
    '4.10':[F('LEFT persistence','foc_thesis','foc_thesis.vesc_runtime_mirror.left.last_persistence','string',true),F('RIGHT persistence','foc_thesis','foc_thesis.vesc_runtime_mirror.right.last_persistence','string',true),F('Physical calibration enabled','esc','esc_ackermann.ros__parameters.steering_physical_calibration_enabled','bool',true)],
    '4.11':[]
  }

};
function experimentSortKey(id){const final=id.startsWith('F')?1:0;const nums=(id.match(/\d+/g)||[]).map(Number);return [final,...nums]}
function compareExperiment(a,b){const A=experimentSortKey(a.id),B=experimentSortKey(b.id);for(let i=0;i<Math.max(A.length,B.length);i++){const d=(A[i]??-1)-(B[i]??-1);if(d)return d}return a.id.localeCompare(b.id)}
function experimentPhase(x){
  const id=String(x?.id||'');
  if(currentExp==='navigation'){
    const n=Number((id.match(/^N(\d+)/)||[])[1]);
    if(Number.isFinite(n)){if(n<=6)return'foundation';if(n<=9)return'localization';if(n<=15)return'autonomy';return'certification'}
    return'bab4';
  }
  if(currentExp==='perception'){
    if(id.startsWith('F'))return'final';const m=Number((id.match(/^4\.(\d+)/)||[])[1]);
    if(m<=2)return'pipeline';if(m===3)return'calibration';if(m<=5)return'scene';if(m<=7)return'safety';return'validation';
  }
  const m=Number((id.match(/^4\.(\d+)/)||[])[1]);
  if(m<=2)return'setup';if(m===3)return'foc';if(m<=5)return'outer';if(m<=8)return'dynamics';return'final';
}
function phaseLabel(k){return {foundation:'Foundation / Sensors',localization:'Localization / EKF',autonomy:'Planning / Control',certification:'End-to-End / Certification',bab4:'BAB IV Source',pipeline:'Camera / Detection',calibration:'Metric Calibration',scene:'Drivable / Lane',safety:'Safety Integration',validation:'Realtime / End-to-End',setup:'Setup / Calibration',foc:'FOC Current Loop',outer:'Outer Loop / Step',dynamics:'Dynamic Validation',final:'Final / Handoff'}[k]||k}
function effectiveExperimentList(){return [...(experiments[currentExp]||[])].sort(compareExperiment)}
function navigationReportBlueprints(){return [
  {id:'R4.1.1',group:'4.1 Pengujian Sensor',title:'Pengujian dan Analisis GNSS',sources:['N5.1'],fieldKeys:['nav_rate','min_sat','max_dop','max_hacc','max_sacc'],tables:[['Variasi','Mean Satelit','Mean DOP','Mean HDOP','Mean hAcc','Quality Gate Pass [%]','Mean Rate GNSS','Max Age GNSS'],['Variasi','Std East [m]','Std North [m]','2D RMS [m]','R95 [m]','Samples']],tableNames:['Tabel 4.1–4.2 Kualitas dan Ringkasan GNSS Aktual','Tabel 4.3 Sebaran Error Posisi GNSS Aktual'],liveSeries:{'Satelit':'gnss_quality.sat','pDOP':'gnss_quality.dop','HDOP':'gnss_quality.hdop','hAcc':'gnss_quality.hacc_m','Rate GNSS':'derived.rate_gnss_hz','Age GNSS':'derived.age_gnss_s','Quality Gate Pass':'derived.gnss_quality_pass'},graphCaptions:['Sebaran posisi GNSS aktual','Kualitas fix GNSS terhadap waktu'],graphs:[{type:'scatter',xSeries:'gnss_fix.lon',ySeries:'gnss_fix.lat',xLabel:'East lokal dari GNSS raw [m]',yLabel:'North lokal dari GNSS raw [m]'},{type:'time_series',series:['pDOP','hAcc','Satelit'],xLabel:'Waktu [s]',yLabel:'Kualitas GNSS raw'}]},
  {id:'R4.1.2',group:'4.1 Pengujian Sensor',title:'Pengujian IMU',sources:['N4.1','N4.2'],fieldKeys:['yaw_offset','gyro_bias_z','r_imu_yaw','r_imu_w'],tables:[['Variasi','Mean Gyro X','Mean Gyro Y','Mean Gyro Z','Std Gyro Z','Mean Yaw','Std Yaw'],['Variasi','RMSE yaw-rate','Mean Gyro Z','Mean Yaw-rate kinematic','Max residual']],tableNames:['Tabel 4.5–4.6 Statistik Gyroscope IMU Aktual','Tabel 4.7 Validasi Heading / Yaw-rate IMU Aktual'],liveSeries:{'Gyro X':'imu.gx','Gyro Y':'imu.gy','Gyro Z':'imu.gz','Yaw':'imu.yaw_rad','IMU wz':'imu.gz','Ackermann wz':'esc_kinematic_yaw_rate'},graphCaptions:['Noise gyro-Z IMU saat diam','Linearitas / respons heading IMU'],graphs:[{type:'time_series',series:['Gyro Z'],xLabel:'Waktu [s]',yLabel:'Gyro-Z [rad/s]'},{type:'time_series',series:['Yaw'],xLabel:'Waktu [s]',yLabel:'Heading IMU [rad]'}]},
  {id:'R4.1.3',group:'4.1 Pengujian Sensor',title:'Pengujian Encoder Steering dan Feedback RPM',sources:['N2.1','N3.1','N3.2'],fieldKeys:['center','operational','gt_distance','odom_scale','r_v_base','r_v_gain'],tables:[['Variasi','Kecepatan perintah [m/s]','Feedback raw ESC [m/s]','RMSE V GNSS raw vs ESC raw [m/s]','Mean V ESC raw [m/s]','Mean V GNSS raw [m/s]'],['Variasi','Steering perintah [rad]','Feedback encoder raw [rad]','RMSE Steering raw [rad]','Max Steering error raw [rad]']],tableNames:['Tabel 4.8 Feedback Kecepatan Raw ESC Aktual','Tabel 4.9 Feedback Encoder Steering Raw Aktual'],liveSeries:{'Kecepatan perintah':'esc_drive_target','Feedback raw ESC':'esc_drive_raw','V ESC raw':'esc_drive_raw','V GNSS raw':'gnss_quality.ground_speed_mps','Steering perintah':'esc_steer_target','Feedback encoder raw':'esc_steer_feedback_raw'},graphCaptions:['Perintah vs feedback kecepatan raw ESC','Perintah vs feedback encoder steering raw'],graphs:[{type:'time_series',series:['Kecepatan perintah','Feedback raw ESC'],xLabel:'Waktu [s]',yLabel:'Kecepatan [m/s]'},{type:'time_series',series:['Steering perintah','Feedback encoder raw'],xLabel:'Waktu [s]',yLabel:'Steering [rad]'}]},

  {id:'R4.2.1',group:'4.2 Extended Kalman Filter Lokal',title:'Pengujian Parameter Frequency',sources:['N7.1'],fieldKeys:['frequency'],tables:[['Variasi','Frequency','RMSE Residual vx ESC','RMSE Residual vx GNSS','Mean EKF age','P95 EKF age','EKF continuity [%]']],tableNames:['Tabel 4.10 Pengujian Frequency EKF Lokal Aktual'],liveSeries:{'Residual vx ESC':'derived.ekf_local_res_vx_esc','Residual vx GNSS':'derived.ekf_local_res_vx_gnss','EKF age':'derived.age_ekf_local_s','EKF continuity':'derived.ekf_local_fresh'},graphCaptions:['Pengaruh frequency terhadap respons EKF lokal'],graphs:[{type:'time_series',series:['Residual vx ESC','Residual vx GNSS','EKF age'],xLabel:'Waktu [s]',yLabel:'Residual / state age'}]},
  {id:'R4.2.2',group:'4.2 Extended Kalman Filter Lokal',title:'Pengujian Parameter sensor_timeout',sources:['N7.1'],fieldKeys:['sensor_timeout'],tables:[['Variasi','Sensor timeout','RMSE Residual vx ESC','RMSE Residual vx GNSS','Mean EKF age','P95 EKF age','EKF continuity [%]']],tableNames:['Tabel 4.11 Pengujian sensor_timeout EKF Lokal Aktual'],liveSeries:{'Residual vx ESC':'derived.ekf_local_res_vx_esc','Residual vx GNSS':'derived.ekf_local_res_vx_gnss','EKF age':'derived.age_ekf_local_s','EKF continuity':'derived.ekf_local_fresh'},graphCaptions:['Pengaruh sensor_timeout EKF lokal'],graphs:[{type:'time_series',series:['EKF age','EKF continuity'],xLabel:'Waktu [s]',yLabel:'State age / continuity'}]},
  {id:'R4.2.3',group:'4.2 Extended Kalman Filter Lokal',title:'Penentuan measurement_noise_covariance Berdasarkan Karakteristik Sensor',sources:['N7.2','N7.3'],fieldKeys:['r_esc_v','r_esc_w','r_imu_yaw','r_imu_w','r_gnss_v_min','r_gnss_v_max'],tables:[['Variasi','R ESC vx','R GNSS vx','R IMU yaw','R ESC wz','R IMU wz','RMSE Residual vx ESC','RMSE Residual vx GNSS']],tableNames:['Tabel 4.12–4.13 Measurement Covariance R EKF Lokal Aktual'],liveSeries:{'R ESC vx':'esc_odom.var_v','R GNSS vx':'gnss_base_vel_fusion.cov_x','R IMU yaw':'imu.var_yaw','R ESC wz':'esc_odom.var_w','R IMU wz':'imu.var_gz','Residual vx ESC':'derived.ekf_local_res_vx_esc','Residual vx GNSS':'derived.ekf_local_res_vx_gnss'},graphCaptions:['Sensitivitas measurement covariance EKF lokal'],graphs:[{type:'time_series',series:['R ESC vx','R GNSS vx','R IMU wz'],xLabel:'Waktu [s]',yLabel:'Measurement variance'}]},
  {id:'R4.2.4',group:'4.2 Extended Kalman Filter Lokal',title:'Pengujian process_noise_covariance',sources:['N7.2','N7.3'],fieldKeys:['qx','qy','qyaw','qvx','qwz'],tables:[['Variasi','Qx','Qy','Qyaw','Qvx','Qwz','Mean sigma X','Mean sigma Y','RMSE Residual vx ESC','RMSE Residual vx GNSS']],tableNames:['Tabel 4.14 Pengujian Process Noise Q EKF Lokal Aktual'],liveSeries:{'sigma X':'derived.ekf_local_sigma_x','sigma Y':'derived.ekf_local_sigma_y','Residual vx ESC':'derived.ekf_local_res_vx_esc','Residual vx GNSS':'derived.ekf_local_res_vx_gnss'},graphCaptions:['Pengaruh process noise EKF lokal'],graphs:[{type:'time_series',series:['sigma X','sigma Y','Residual vx ESC'],xLabel:'Waktu [s]',yLabel:'Uncertainty / residual'}]},
  {id:'R4.2.5',group:'4.2 Extended Kalman Filter Lokal',title:'Pengujian predict_to_current_time',sources:['N7.1','N7.4'],fieldKeys:['predict'],tables:[['Variasi','Predict to current time','RMSE Residual vx ESC','RMSE Residual vx GNSS','Mean EKF age','P95 EKF age','EKF continuity [%]']],tableNames:['Tabel 4.15 Pengujian predict_to_current_time EKF Lokal Aktual'],liveSeries:{'Residual vx ESC':'derived.ekf_local_res_vx_esc','Residual vx GNSS':'derived.ekf_local_res_vx_gnss','EKF age':'derived.age_ekf_local_s','EKF continuity':'derived.ekf_local_fresh'},graphCaptions:['Pengaruh predict_to_current_time EKF lokal'],graphs:[{type:'time_series',series:['EKF age','Residual vx ESC'],xLabel:'Waktu [s]',yLabel:'State age / residual'}]},

  {id:'R4.3.1',group:'4.3 Extended Kalman Filter Global',title:'Pengujian Parameter Frequency',sources:['N8.1'],fieldKeys:['frequency'],tables:[['Variasi','Frequency','RMSE Residual XY GNSS [m]','Mean EKF age','P95 EKF age','EKF global continuity [%]','GNSS availability [%]']],tableNames:['Tabel 4.16 Pengujian Frequency EKF Global Aktual'],liveSeries:{'Residual XY GNSS':'derived.ekf_global_res_xy','EKF age':'derived.age_ekf_global_s','EKF global continuity':'derived.ekf_global_fresh','GNSS availability':'derived.gnss_available'},graphCaptions:['Pengaruh frequency EKF global'],graphs:[{type:'time_series',series:['Residual XY GNSS','EKF age'],xLabel:'Waktu [s]',yLabel:'Residual posisi / state age'}]},
  {id:'R4.3.2',group:'4.3 Extended Kalman Filter Global',title:'Pengujian Parameter sensor_timeout',sources:['N8.1'],fieldKeys:['sensor_timeout'],tables:[['Variasi','Sensor timeout','GNSS availability [%]','Longest GNSS gap [s]','EKF global continuity [%]','RMSE Residual XY GNSS [m]','Mean EKF age']],tableNames:['Tabel 4.17 Pengujian sensor_timeout EKF Global Aktual'],liveSeries:{'GNSS availability':'derived.gnss_available','EKF global continuity':'derived.ekf_global_fresh','Residual XY GNSS':'derived.ekf_global_res_xy','EKF age':'derived.age_ekf_global_s'},graphCaptions:['Pengaruh sensor_timeout EKF global'],graphs:[{type:'time_series',series:['GNSS availability','EKF global continuity','Residual XY GNSS'],xLabel:'Waktu [s]',yLabel:'Availability / residual'}]},
  {id:'R4.3.3',group:'4.3 Extended Kalman Filter Global',title:'Penentuan measurement_noise_covariance GNSS',sources:['N8.2','N8.3','N5.1'],fieldKeys:['r_gnss_v_min','r_gnss_v_max','r_cog_min','r_cog_max','r_imu_w'],tables:[['Variasi','Mean hAcc','R GNSS X','R GNSS Y','R GNSS vx','R COG yaw','RMSE Residual XY GNSS [m]','Max position jump [m]']],tableNames:['Tabel 4.18–4.19 Measurement Covariance GNSS Aktual'],liveSeries:{'hAcc':'gnss_quality.hacc_m','R GNSS X':'gnss_map_odom.var_x','R GNSS Y':'gnss_map_odom.var_y','R GNSS vx':'gnss_base_vel_fusion.cov_x','R COG yaw':'gnss_cog_fusion.yaw_variance','Residual XY GNSS':'derived.ekf_global_res_xy','Position jump':'derived.ekf_global_jump_m'},graphCaptions:['Sensitivitas measurement covariance GNSS'],graphs:[{type:'time_series',series:['R GNSS X','R GNSS Y','Residual XY GNSS'],xLabel:'Waktu [s]',yLabel:'Position variance / residual'}]},
  {id:'R4.3.4',group:'4.3 Extended Kalman Filter Global',title:'Pengujian process_noise_covariance Posisi X-Y',sources:['N8.2','N8.3'],fieldKeys:['qx','qy'],tables:[['Variasi','Qx','Qy','Mean sigma X','Mean sigma Y','RMSE Residual XY GNSS [m]','Max position jump [m]']],tableNames:['Tabel 4.20 Pengujian Process Noise Posisi EKF Global Aktual'],liveSeries:{'sigma X':'derived.ekf_global_sigma_x','sigma Y':'derived.ekf_global_sigma_y','Residual XY GNSS':'derived.ekf_global_res_xy','Position jump':'derived.ekf_global_jump_m'},graphCaptions:['Pengaruh process noise posisi EKF global'],graphs:[{type:'time_series',series:['sigma X','sigma Y','Residual XY GNSS'],xLabel:'Waktu [s]',yLabel:'Uncertainty / residual [m]'}]},
  {id:'R4.3.5',group:'4.3 Extended Kalman Filter Global',title:'Pengujian predict_to_current_time',sources:['N8.1','N8.4'],fieldKeys:['predict'],tables:[['Variasi','Predict to current time','RMSE Residual XY GNSS [m]','Max position jump [m]','Mean EKF age','P95 EKF age','EKF global continuity [%]']],tableNames:['Tabel 4.21 Pengujian predict_to_current_time EKF Global Aktual'],liveSeries:{'Residual XY GNSS':'derived.ekf_global_res_xy','Position jump':'derived.ekf_global_jump_m','EKF age':'derived.age_ekf_global_s','EKF global continuity':'derived.ekf_global_fresh'},graphCaptions:['Pengaruh predict_to_current_time EKF global'],graphs:[{type:'time_series',series:['Residual XY GNSS','Position jump','EKF age'],xLabel:'Waktu [s]',yLabel:'Residual / jump / state age'}]},

  {id:'R4.4.1',group:'4.4 Smac Hybrid-A* Planner',title:'Pengujian minimum_turning_radius',sources:['N11.1'],fieldKeys:['rmin'],runFields:[RUN('rmin_candidate','minimum_turning_radius candidate [m]','float','0.40','Variasi Percobaan')],tables:[['Variasi','minimum_turning_radius candidate [m]','Planning time','Path length','Path endpoint error','Minimum clearance [m]','Planner success']],tableNames:['Tabel 4.22 Pengujian minimum_turning_radius Aktual'],liveSeries:{'Planning time':'nav_path.planning_latency_ms','Path length':'nav_path.length_m','Path endpoint error':'derived.path_endpoint_error_m','Minimum clearance':'derived.global_path_min_clearance_m'},graphCaptions:['Pengaruh minimum turning radius'],graphs:[{type:'path',pathKey:'nav_path',xLabel:'Map X [m]',yLabel:'Map Y [m]'}]},
  {id:'R4.4.2',group:'4.4 Smac Hybrid-A* Planner',title:'Pengujian downsampling_factor',sources:['N11.1'],fieldKeys:['downsample','factor'],tables:[['Variasi','Downsample costmap','Downsampling factor','Planning time','Path length','Minimum clearance [m]','Planner success']],tableNames:['Tabel 4.23 Pengujian downsampling_factor Aktual'],liveSeries:{'Planning time':'nav_path.planning_latency_ms','Path length':'nav_path.length_m','Minimum clearance':'derived.global_path_min_clearance_m'},graphCaptions:['Trade-off downsampling factor'],graphs:[{type:'time_series',series:['Planning time','Minimum clearance'],xLabel:'Waktu [s]',yLabel:'Planning time / clearance'}]},
  {id:'R4.4.3',group:'4.4 Smac Hybrid-A* Planner',title:'Pengujian Parameter tolerance dan Validasi Endpoint Error',sources:['N11.1'],fieldKeys:[],extraFields:[F('Planner tolerance (m)','nav2','planner_server.ros__parameters.GridBased.tolerance','float',false,'Tolerance Smac Hybrid-A*: uji OFAT dan validasi endpoint error sebelum memilih nilai final.')],tables:[['Variasi','Planner tolerance (m)','Path endpoint error','Planning time','Planner success','Path length']],tableNames:['Tabel 4.24 Pengujian Planner Tolerance dan Endpoint Error Aktual'],liveSeries:{'Path endpoint error':'derived.path_endpoint_error_m','Planning time':'nav_path.planning_latency_ms','Path length':'nav_path.length_m'},graphCaptions:['Pengaruh planner tolerance terhadap endpoint error'],graphs:[{type:'time_series',series:['Path endpoint error','Planning time'],xLabel:'Waktu [s]',yLabel:'Endpoint error / planning time'}]},
  {id:'R4.4.4',group:'4.4 Smac Hybrid-A* Planner',title:'Pengujian cost_penalty',sources:['N11.1'],fieldKeys:['cost_penalty'],tables:[['Variasi','Cost penalty','Minimum clearance [m]','Path length','Planning time','Planner success']],tableNames:['Tabel 4.25 Pengujian cost_penalty Aktual'],liveSeries:{'Minimum clearance':'derived.global_path_min_clearance_m','Path length':'nav_path.length_m','Planning time':'nav_path.planning_latency_ms'},graphCaptions:['Pengaruh cost_penalty'],graphs:[{type:'time_series',series:['Minimum clearance','Path length','Planning time'],xLabel:'Waktu [s]',yLabel:'Clearance / path length / planning time'}]}
]}
function navigationReportList(){
  const src=experiments.navigation||[],byId=id=>src.find(x=>x.id===id);
  return navigationReportBlueprints().map(bp=>{const ss=bp.sources.map(byId).filter(Boolean);if(!ss.length)return null;const dedupe=(arr,keyFn)=>{const seen=new Set();return arr.filter(v=>{const k=keyFn(v);if(seen.has(k))return false;seen.add(k);return true})};let fields=dedupe(ss.flatMap(x=>x.parameterFields||[]),p=>`${p.yamlFileKey||''}:${p.yamlPath||p.key||p.label}`);if(bp.fieldKeys)fields=fields.filter(p=>bp.fieldKeys.includes(String(p.key||'')));fields=dedupe([...fields,...(bp.extraFields||[]),...(bp.runFields||[])],p=>`${p.yamlFileKey||''}:${p.yamlPath||p.key||p.label}`);if(bp.freeze)fields=fields.map(p=>p.yamlFileKey?{...p,kind:'yaml_readonly',locked:true,group:p.group||'FROZEN CONFIG'}:p);const graphCaptions=bp.graphCaptions||ss.flatMap(x=>x.graphCaptions||[]),graphs=bp.graphs||ss.flatMap(x=>x.graphs||[]),liveSeries=bp.liveSeries||Object.assign({},...ss.map(x=>x.liveSeries||{}));return {id:bp.id,groupId:bp.group,groupTitle:bp.group,section:`${bp.id.slice(1)} ${bp.title}`,reportMode:true,sourceIds:bp.sources,parameterFields:fields,tableColumns:bp.tables||ss.flatMap(x=>x.tableColumns||[]),tableNames:bp.tableNames||ss.flatMap(x=>x.tableNames||[]),graphCaptions,graphs,liveSeries}}
  ).filter(Boolean)
}
function findExperimentById(id){return (experiments[currentExp]||[]).find(v=>v.id===id)||(currentExp==='navigation'?navigationReportList().find(v=>v.id===id):null)}
function displayExperimentId(x){const id=String(x?.id||'');let m;if((m=id.match(/^R(4\.\d+\.\d+)$/)))return m[1];if((m=id.match(/^N(\d+)\.(\d+)$/)))return `${+m[1]}.${+m[2]}`;if((m=id.match(/^4\.(\d+)\.(\d+)$/)))return `${+m[1]}.${+m[2]}`;if((m=id.match(/^4\.(\d+)$/)))return `${+m[1]}.1`;if((m=id.match(/^F4\.(\d+)$/)))return `Final ${+m[1]}.1`;return id.replace(/^N(?=\d)/,'')}
function reportRunId(x=selectedExperiment,domain=currentExp){const id=String(x?.id||'').trim();if(domain==='navigation'){if(/^R4\.[1-4]\.[1-5]$/.test(id))return `BAB4_${displayExperimentId(x)}`;return /^N\d+\.\d+$/.test(id)?id:`N${displayExperimentId(x)}`}let d=displayExperimentId(x).replace(/^Final\s+/i,'').replace(/[^0-9.]/g,'');if(!d)d='0.0';return (domain==='perception'?'P':'E')+d}
function stripCatalogPrefix(text=''){return String(text).replace(/^FINAL BAB IV\s*[—-]\s*/i,'').replace(/^N\d+(?:\.\d+)?\s+/,'').replace(/^4\.\d+(?:\.\d+)?\s+/,'').trim()}
function displayExperimentTitle(x){return stripCatalogPrefix(x?.section||x?.id||'').replace(/^\d+(?:\.\d+){1,2}\s+/,'').trim()}
function displayExperimentGroup(x){if(String(x?.id||'').startsWith('F'))return 'Final Dataset';return stripCatalogPrefix(x?.groupTitle||x?.groupId||'Tuning')||'Tuning'}
const RUN=(key,label,kind='float',placeholder='',group='Variasi Percobaan')=>({key,label,kind,placeholder,group,yamlFileKey:'',yamlPath:'',isGroundTruth:false,locked:false});
const STEERING_RUN_FIELDS={
'4.2.1':[RUN('repeat_count','Jumlah snapshot','int','3')],
'4.2.2':[RUN('stationary_duration_s','Durasi stationary (s)','float','15')],
'4.2.3':[RUN('cycle_count','Siklus LEFT/CENTER/RIGHT','int','5')],
'4.2.4':[RUN('detect_current_a','Arus detect encoder (A)','float','1.5')],
'4.2.5':[RUN('test_erpm','RIGHT test eRPM','float','100'),RUN('detect_current_a','Hall detect current (A)','float','1.0')],
'4.3.1':[RUN('iq_ref_a','LEFT Iq reference (A)','float','1.0'),RUN('gain_variant','Gain variant','string','baseline')],
'4.3.2':[RUN('iq_ref_a','RIGHT Iq reference (A)','float','2.0'),RUN('gain_variant','Gain variant','string','baseline')],
'4.4.1':[RUN('test_steering_deg','Steering step (deg)','float','10'),RUN('gain_variant','PID variant','string','baseline')],
'4.4.2':[RUN('test_erpm','RIGHT test eRPM','float','200'),RUN('gain_variant','PID variant','string','baseline')],
'4.5.1':[RUN('test_steering_deg','Steering step (deg)','float','10'),RUN('repeat_count','Repeat per direction','int','3')],
'4.5.2':[RUN('command_mode','Command mode','string','RPM'),RUN('command_value','Command value','float','200')],
'4.6.1':[RUN('test_steering_deg','Steering magnitude (deg)','float','20')],
'4.6.2':[RUN('cycle_count','Jumlah L/C/R cycle','int','5')],
'4.6.3':[RUN('test_steering_deg','Steering (deg)','float','10'),RUN('test_erpm','RIGHT eRPM','float','100')],
'4.7.1':[RUN('sine_amplitude_deg','Sine amplitude (deg)','float','10'),RUN('sine_frequency_hz','Sine frequency (Hz)','float','0.2')],
'4.7.2':[RUN('test_erpm','Velocity target eRPM','float','200')],
'4.8.1':[RUN('load_level','Load / disturbance','string','light'),RUN('test_steering_deg','Steering target (deg)','float','0')],
'4.8.2':[RUN('load_level','Load / disturbance','string','light'),RUN('test_erpm','RIGHT target eRPM','float','200')],
'4.9':[RUN('final_scenario','Final validation scenario','string','combined-safe')]
};
function tuningFieldsFor(x){
  const catalog=[...(x?.parameterFields||[])];
  const web=[...(WEB_TUNING[currentExp]?.[x?.id]||[])];
  let base=catalog.some(p=>p.yamlFileKey)?catalog:(catalog.length?[...catalog,...web]:web);
  if(currentExp==='steering')base=[...(STEERING_RUN_FIELDS[x?.id]||[]),...base];
  const seen=new Set(),out=[];for(const p of base){const k=`${p.yamlFileKey||''}:${p.yamlPath||p.key||p.label}`;if(seen.has(k))continue;seen.add(k);out.push(p)}return out
}
function configValue(file,path){let n=configs[file]?.data;if(n==null)return undefined;for(const part of String(path||'').split('.').filter(Boolean)){if(Array.isArray(n)&&/^\d+$/.test(part))n=n[+part];else if(n&&typeof n==='object')n=n[part];else return undefined}return n}
function baselineConfigValue(file,path){let n=configs[file]?.baseline_data;if(n==null)return undefined;for(const part of String(path||'').split('.').filter(Boolean)){if(Array.isArray(n)&&/^\d+$/.test(part))n=n[+part];else if(n&&typeof n==='object'&&Object.prototype.hasOwnProperty.call(n,part))n=n[part];else return undefined}return n}
function baselineText(v,max=42){if(v===undefined)return'';const s=Array.isArray(v)||v&&typeof v==='object'?JSON.stringify(v):String(v);return s.length>max?s.slice(0,max-1)+'…':s}
function baseMetric(path){if(Object.prototype.hasOwnProperty.call(state,path))return state[path];const parts=String(path||'').split('.');for(let n=parts.length-1;n>0;n--){const root=parts.slice(0,n).join('.');if(Object.prototype.hasOwnProperty.call(state,root)){let v=state[root];for(const p of parts.slice(n)){if(v==null)return undefined;v=v[p]}return v}}return undefined}
function ekfDiagnosticMetric(path){
  const num=k=>{const v=baseMetric(k);return Number.isFinite(+v)?+v:NaN},positive=v=>Number.isFinite(v)&&v>=0;
  const sigma=p=>positive(p)?Math.sqrt(p):undefined,gain=(p,r)=>positive(p)&&positive(r)&&p+r>1e-15?Math.max(0,Math.min(1,p/(p+r))):undefined;
  const residual=(m,e,angular=false)=>Number.isFinite(m)&&Number.isFinite(e)?(angular?wrapPi(m-e):m-e):undefined;
  const nis=(res,pv,r)=>Number.isFinite(res)&&positive(pv)&&positive(r)&&pv+r>1e-15?res*res/(pv+r):undefined;
  const local=path.startsWith('derived.ekf_local_'),prefix=local?'ekf_local.':'ekf_global.',tail=path.slice((local?'derived.ekf_local_':'derived.ekf_global_').length);
  const px=num(prefix+'var_x'),py=num(prefix+'var_y'),pyaw=num(prefix+'var_yaw'),pv=num(prefix+'var_v'),pw=num(prefix+'var_w');
  const pMap={sigma_x:px,sigma_y:py,sigma_yaw:pyaw,sigma_vx:pv,sigma_w:pw};if(Object.prototype.hasOwnProperty.call(pMap,tail))return sigma(pMap[tail]);
  if(tail.startsWith('p_growth_')){const name=tail.slice('p_growth_'.length),val={x:px,y:py,yaw:pyaw,vx:pv,w:pw}[name];if(!positive(val))return undefined;const now=Date.now(),key=prefix+name,prev=ekfGrowthState.get(key);ekfGrowthState.set(key,{t:now,p:val});return prev&&now>prev.t?(val-prev.p)/((now-prev.t)/1000):undefined}
  if(local){const rEscV=num('esc_odom.var_v'),rEscW=num('esc_odom.var_w'),rImuYaw=num('imu.var_yaw'),rImuW=num('imu.var_gz'),rGnssV=num('gnss_base_vel_fusion.cov_x'),eV=num('ekf_local.v'),eW=num('ekf_local.w'),eYaw=num('ekf_local.yaw'),mEscV=num('esc_odom.v'),mEscW=num('esc_odom.w'),mGnssV=num('gnss_base_vel_fusion.vx'),mImuW=num('imu.gz'),mImuYaw=num('imu.yaw_rad');
    const gains={k_vx_esc:gain(pv,rEscV),k_vx_gnss:gain(pv,rGnssV),k_yaw_imu:gain(pyaw,rImuYaw),k_w_esc:gain(pw,rEscW),k_w_imu:gain(pw,rImuW)};if(tail in gains)return gains[tail];
    const res={res_vx_esc:residual(mEscV,eV),res_vx_gnss:residual(mGnssV,eV),res_yaw_imu:residual(mImuYaw,eYaw,true),res_w_esc:residual(mEscW,eW),res_w_imu:residual(mImuW,eW)};if(tail in res)return res[tail];
    const nisMap={nis_vx_esc:nis(res.res_vx_esc,pv,rEscV),nis_vx_gnss:nis(res.res_vx_gnss,pv,rGnssV),nis_yaw_imu:nis(res.res_yaw_imu,pyaw,rImuYaw),nis_w_esc:nis(res.res_w_esc,pw,rEscW),nis_w_imu:nis(res.res_w_imu,pw,rImuW)};if(tail in nisMap)return nisMap[tail];
  }else{const rX=num('gnss_map_odom.var_x'),rY=num('gnss_map_odom.var_y'),rV=num('gnss_base_vel_fusion.cov_x'),rCog=num('gnss_cog_fusion.yaw_variance'),rImuW=num('imu.var_gz'),ex=num('ekf_global.x'),ey=num('ekf_global.y'),ev=num('ekf_global.v'),ew=num('ekf_global.w'),eyaw=num('ekf_global.yaw'),mx=num('gnss_map_odom.x'),my=num('gnss_map_odom.y'),mv=num('gnss_base_vel_fusion.vx'),mcog=num('gnss_cog_fusion.yaw_rad'),miw=num('imu.gz');
    const gains={k_x_gnss:gain(px,rX),k_y_gnss:gain(py,rY),k_vx_gnss:gain(pv,rV),k_yaw_cog:gain(pyaw,rCog),k_w_imu:gain(pw,rImuW)};if(tail in gains)return gains[tail];
    const res={res_x_gnss:residual(mx,ex),res_y_gnss:residual(my,ey),res_vx_gnss:residual(mv,ev),res_yaw_cog:residual(mcog,eyaw,true),res_w_imu:residual(miw,ew)};if(tail in res)return res[tail];
    const nisMap={nis_x_gnss:nis(res.res_x_gnss,px,rX),nis_y_gnss:nis(res.res_y_gnss,py,rY),nis_vx_gnss:nis(res.res_vx_gnss,pv,rV),nis_yaw_cog:nis(res.res_yaw_cog,pyaw,rCog),nis_w_imu:nis(res.res_w_imu,pw,rImuW)};if(tail in nisMap)return nisMap[tail];
  }return undefined
}
function resolveMetricPath(path){if(!path)return undefined;if(path==='derived.cte_m')return derivedCte();if(path==='derived.endpoint_error_m')return derivedEndpoint();if(path==='derived.path_endpoint_error_m')return derivedPathEndpointError();if(path==='derived.path_heading_error_rad')return derivedHeadingError();if(path==='derived.velocity_error_mps')return (+raw('esc_drive_actual')||0)-(+obj('cmd_final').linear_x||0);if(path==='derived.ackermann_yaw_error')return Number.isFinite(+raw('esc_yaw_rate'))&&Number.isFinite(+raw('esc_kinematic_yaw_rate'))?(+raw('esc_yaw_rate'))-(+raw('esc_kinematic_yaw_rate')):undefined;if(path==='derived.steering_error_rad')return (+raw('esc_steer_actual')||0)-(+raw('esc_steer_target')||0);if(path==='derived.gnss_quality_pass')return gnssQualityPassValue();if(path==='derived.gnss_available')return gnssAvailableValue();if(path==='derived.ekf_local_fresh')return ekfFreshValue('local');if(path==='derived.ekf_global_fresh')return ekfFreshValue('global');if(path==='derived.ekf_global_res_xy')return globalResidualXY();if(path==='derived.ekf_global_jump_m')return globalPositionJump();if(path==='derived.global_path_min_clearance_m')return globalPathCostmapMetrics()?.minClearance;if(path==='derived.global_path_lethal_valid')return globalPathCostmapMetrics()?.valid;const timing={
  'derived.rate_gnss_hz':['rate','gnss_fix'],'derived.rate_imu_hz':['rate','imu'],'derived.rate_esc_hz':['rate','esc_odom'],'derived.rate_ekf_local_hz':['rate','ekf_local'],'derived.rate_ekf_global_hz':['rate','ekf_global'],
  'derived.dt_gnss_s':['dt','gnss_fix'],'derived.dt_imu_s':['dt','imu'],'derived.dt_esc_s':['dt','esc_odom'],
  'derived.age_gnss_s':['age','gnss_fix'],'derived.age_imu_s':['age','imu'],'derived.age_esc_s':['age','esc_odom'],'derived.age_ekf_local_s':['age','ekf_local'],'derived.age_ekf_global_s':['age','ekf_global']};
  if(timing[path]){const [kind,k]=timing[path];return kind==='rate'?channelRate(k):kind==='dt'?channelDt(k):age(k)}if(path.startsWith('derived.ekf_'))return ekfDiagnosticMetric(path);return baseMetric(path)}
function metricPathCaptureAllowed(path){
  const p=String(path||'');
  if(p.startsWith('derived.')){
    if(/^derived\.(age_|gnss_available|ekf_(local|global)_fresh)/.test(p))return true;
    const deps=typeof derivedMetricDependencies==='function'?derivedMetricDependencies(p):[];
    if(!deps.length)return true;
    return deps.every(d=>{const v=baseMetric(d);if(v===undefined||v===null)return false;const info=typeof metricStatePathInfo==='function'?metricStatePathInfo(d):{root:String(d).split('.')[0]};if(typeof metricRootIsLive==='function'&&metricRootIsLive(info.root)){const f=metricRootFreshness(info.root);if(!f.fresh)return false}return true});
  }
  const info=typeof metricStatePathInfo==='function'?metricStatePathInfo(p):{root:p.split('.')[0]};
  if(typeof metricRootIsLive==='function'&&metricRootIsLive(info.root)){const f=metricRootFreshness(info.root);if(!f.fresh)return false}
  return true;
}
function currentPose(){const g=obj('ekf_global');if(Number.isFinite(+g.x))return g;const l=obj('ekf_local');return Number.isFinite(+l.x)?l:null}
function nearestPathInfo(){const pose=currentPose(),pts=obj('local_path').points||obj('nav_path').points||[];if(!pose||!pts.length)return null;let best=null;for(const p of pts){const d=Math.hypot((+p[0])-pose.x,(+p[1])-pose.y);if(!best||d<best.d)best={d,p}}return best}
function derivedCte(){return nearestPathInfo()?.d}
function derivedEndpoint(){const pose=currentPose(),goal=obj('goal_pose');if(!pose||!Number.isFinite(+goal.x))return undefined;return Math.hypot(pose.x-goal.x,pose.y-goal.y)}
function derivedPathEndpointError(){const pts=obj('nav_path').points||[],goal=obj('goal_pose');if(!pts.length||!Number.isFinite(+goal.x)||!Number.isFinite(+goal.y))return undefined;const p=pts[pts.length-1];return Array.isArray(p)&&Number.isFinite(+p[0])&&Number.isFinite(+p[1])?Math.hypot(+p[0]-+goal.x,+p[1]-+goal.y):undefined}
function plannerPathSuccess(){const pts=obj('nav_path').points||[];return pts.length>=2&&Number.isFinite(+obj('nav_path').length_m)?'PASS':'WAIT'}
function gnssQualityPassValue(){const q=obj('gnss_quality'),sat=+q.sat,dop=+(q.dop??q.pdop??q.hdop),hacc=+q.hacc_m,minSat=+configValue('gnss','data_cuav_node.ros__parameters.min_satellites'),maxDop=+configValue('gnss','data_cuav_node.ros__parameters.max_dop'),maxHacc=+configValue('gnss','data_cuav_node.ros__parameters.max_hacc_m');if(![sat,dop,hacc].every(Number.isFinite))return undefined;if(q.gnss_fix_ok===false)return 0;return (sat>=(Number.isFinite(minSat)?minSat:0)&&dop<=(Number.isFinite(maxDop)?maxDop:Infinity)&&hacc<=(Number.isFinite(maxHacc)?maxHacc:Infinity))?1:0}
function ekfFreshValue(which){const key=which==='local'?'ekf_local':'ekf_global',path=which==='local'?'ekf_filter_node_odom.ros__parameters.sensor_timeout':'ekf_filter_node_map.ros__parameters.sensor_timeout',cfg=+configValue('ekf',path),limit=Math.max(.05,Number.isFinite(cfg)?cfg:.5);return Number.isFinite(age(key))?(age(key)<=limit?1:0):undefined}
function gnssAvailableValue(){if(!bool(raw('connected.gnss')))return 0;const a=age('gnss_fix');if(!Number.isFinite(a)||a>1.5)return 0;return obj('gnss_quality').gnss_fix_ok===false?0:1}
function globalResidualXY(){const g=obj('gnss_map_odom'),e=obj('ekf_global');return [g.x,g.y,e.x,e.y].every(v=>Number.isFinite(+v))?Math.hypot(+g.x-+e.x,+g.y-+e.y):undefined}
function globalPositionJump(){const e=obj('ekf_global');if(!Number.isFinite(+e.x)||!Number.isFinite(+e.y))return undefined;const sec=labElapsedSecond(),key='global_jump',prev=reportDerivedCache.get(key);if(prev&&prev.sec===sec)return prev.value;const value=prev?Math.hypot(+e.x-prev.x,+e.y-prev.y):0;reportDerivedCache.set(key,{sec,x:+e.x,y:+e.y,value});return value}
function longestZeroRunSeconds(path){const a=metricHistory.get(path)||[];let best=0,start=null,last=null;for(const p of a){if(p.v<.5){if(start===null)start=p.s;last=p.s}else if(start!==null){best=Math.max(best,(last??start)-start+1);start=last=null}}if(start!==null)best=Math.max(best,(last??start)-start+1);return best}
function globalPathCostmapMetrics(){const path=obj('nav_path'),meta=obj('global_costmap_meta'),pts=path.points||[];if(!globalCostmapImage||pts.length<2||!meta.image_width||!meta.image_height||!meta.resolution||!meta.stride)return null;const key=`${meta.at_ms||0}:${path.measurement_stamp_sec||0}:${pts.length}`;if(reportCostmapMetricCache.key===key)return reportCostmapMetricCache;try{const w=+meta.image_width,h=+meta.image_height,cell=+meta.resolution*+meta.stride,c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(globalCostmapImage,0,0,w,h);const d=ctx.getImageData(0,0,w,h).data,lethal=(x,y)=>{if(x<0||y<0||x>=w||y>=h)return false;const i=(y*w+x)*4;return d[i+3]>20&&d[i]>235&&d[i+1]<115};let min=Infinity,valid=1;const sampleStep=Math.max(1,Math.ceil(pts.length/120)),maxR=Math.max(5,Math.min(100,Math.ceil(8/Math.max(cell,.01))));for(let pi=0;pi<pts.length;pi+=sampleStep){const p=pts[pi],mp=framePointToMap(path.frame_id||'map',+p[0],+p[1]);if(!mp)continue;const ix=Math.round((mp.x-+meta.origin_x)/cell),iy=Math.round(h-1-(mp.y-+meta.origin_y)/cell);if(ix<0||iy<0||ix>=w||iy>=h){valid=0;continue}if(lethal(ix,iy))valid=0;let best2=Infinity;for(let dy=-maxR;dy<=maxR;dy++){const yy=iy+dy;if(yy<0||yy>=h)continue;for(let dx=-maxR;dx<=maxR;dx++){const dd=dx*dx+dy*dy;if(dd>=best2)continue;const xx=ix+dx;if(xx<0||xx>=w||!lethal(xx,yy))continue;best2=dd}}if(Number.isFinite(best2))min=Math.min(min,Math.sqrt(best2)*cell)}if(!Number.isFinite(min))min=maxR*cell;reportCostmapMetricCache={key,minClearance:min,valid};return reportCostmapMetricCache}catch(_){return null}}
function wrapPi(v){while(v>Math.PI)v-=2*Math.PI;while(v<-Math.PI)v+=2*Math.PI;return v}
function derivedHeadingError(){const pose=currentPose(),n=nearestPathInfo();if(!pose||!n||!Number.isFinite(+n.p[2]))return undefined;return wrapPi((pose.yaw||0)-(+n.p[2]))}
function reportEvidenceLifecycle(){if(currentExp!=='navigation'||selectedExperiment?.reportMode!==true)return recordStartedMs?'RECORDING':'LIVE';if(recordStartedMs&&!reportEvidenceFrozen)return'RECORDING';if(reportEvidenceFrozen&&reportEvidenceFrozenLeaf===selectedExperiment?.id)return'FROZEN';return'PREVIEW'}
function reportEvidenceHasRecordedData(){const s=reportEvidenceLifecycle();return s==='RECORDING'||s==='FROZEN'}
function reportPathSnapshotKey(index){return `${currentExp}:${selectedExperiment?.id||'none'}:${index}`}
function reportPathData(index,pathKey='nav_path'){const snap=reportPathSnapshots.get(reportPathSnapshotKey(index));if(currentExp==='navigation'&&selectedExperiment?.reportMode===true){if(snap)return snap;if(reportEvidenceLifecycle()==='FROZEN')return {points:[],frame_id:'map'}}return obj(pathKey)}
function labElapsedSecond(now=Date.now()){const origin=recordStartedMs||chartEpochMs||now;return Math.max(0,Math.floor((now-origin)/1000+1e-9))}
function captureTemplateRows(sec){if(!recordStartedMs||!selectedExperiment)return;const yaml=parameterSnapshotEntries().map(x=>({key:`${x.file}:${tuningFieldsFor(selectedExperiment).find(p=>(p.label||p.key||p.yamlPath)===x.label)?.yamlPath||x.key}`,label:x.label,value:x.value}));(selectedExperiment.tableColumns||[]).forEach((cols,ti)=>{if(!cols?.length)return;const a=tableRunRows.get(ti)||[];a.push({sec,values:cols.map(c=>inferColumnValue(c)),yaml});while(a.length>7200)a.shift();tableRunRows.set(ti,a)})}
function captureLabTelemetry(){
  if(!selectedExperiment)return;
  if(currentExp==='navigation'&&selectedExperiment.reportMode===true&&reportEvidenceFrozen&&reportEvidenceFrozenLeaf===selectedExperiment.id)return;
  const now=Date.now(),origin=recordStartedMs||chartEpochMs||now,elapsed=Math.max(0,(now-origin)/1000),tick=Math.floor(elapsed*5),s=tick/5;
  if(tick===lastLabTelemetryTick)return;
  lastLabTelemetryTick=tick;
  window.analysisSession?.syncLive(s);
  const paths=new Set(Object.values(selectedExperiment.liveSeries||{}));
  ['esc_drive_target','esc_drive_actual','esc_steer_target','esc_steer_actual','imu.gx','imu.gy','imu.gz','imu.ax','imu.ay','imu.az','imu.roll_rad','imu.pitch_rad','imu.yaw_rad','imu.var_yaw','imu.var_gx','imu.var_gy','imu.var_gz','gnss_quality.hacc_m','gnss_quality.dop','gnss_quality.hdop','gnss_quality.vdop','gnss_quality.gdop','gnss_quality.sat','gnss_fix.lat','gnss_fix.lon','perception_performance.fps','foc_telemetry.iq_a','foc_telemetry.id_a'].forEach(p=>paths.add(p));
  for(const path of paths){if(!metricPathCaptureAllowed(path))continue;const v=resolveMetricPath(path);if(typeof v!=='number'||!Number.isFinite(v))continue;const a=metricHistory.get(path)||[];a.push({s,t:origin+s*1000,v});while(a.length>7200)a.shift();metricHistory.set(path,a)}
  (selectedExperiment.graphs||[]).forEach((g,gi)=>{const addPoint=(key,xPath,yPath,convertGeo=false)=>{if(!metricPathCaptureAllowed(xPath)||!metricPathCaptureAllowed(yPath))return;let xv=resolveMetricPath(xPath),yv=resolveMetricPath(yPath);if(!Number.isFinite(+xv)||!Number.isFinite(+yv))return;xv=+xv;yv=+yv;if(convertGeo){let o=scatterOrigins.get(key);if(!o){o={lon:xv,lat:yv};scatterOrigins.set(key,o)}const R=6378137,lat0=o.lat*Math.PI/180;xv=(xv-o.lon)*Math.PI/180*R*Math.cos(lat0);yv=(yv-o.lat)*Math.PI/180*R}const a=scatterHistory.get(key)||[];a.push({s,x:xv,y:yv});while(a.length>7200)a.shift();scatterHistory.set(key,a)};if(g?.type==='path'){const d=obj(g.pathKey||'nav_path'),pts=Array.isArray(d.points)?d.points:[];if(pts.length)reportPathSnapshots.set(reportPathSnapshotKey(gi),{...d,points:pts.map(p=>Array.isArray(p)?[...p]:p)})}if(g?.type==='scatter')addPoint(`${currentExp}:${selectedExperiment.id}:${gi}`,g.xSeries,g.ySeries,g.xSeries==='gnss_fix.lon'&&g.ySeries==='gnss_fix.lat');else if(g?.type==='multi_scatter')(g.pairs||[]).forEach((pair,pi)=>{const xp=selectedExperiment.liveSeries?.[pair[0]]||pair[0],yp=selectedExperiment.liveSeries?.[pair[1]]||pair[1];addPoint(`${currentExp}:${selectedExperiment.id}:${gi}:${pi}`,xp,yp,false)})});
  const sec=Math.floor(s+1e-9);if(recordStartedMs&&sec!==lastLabSecond){lastLabSecond=sec;captureTemplateRows(sec)}
}
function visitedKey(){return `adv-visited-${currentExp}`}
function visitedSet(){try{return new Set(JSON.parse(localStorage.getItem(visitedKey())||'[]'))}catch(_){return new Set()}}
function markVisited(id){const s=visitedSet();s.add(id);localStorage.setItem(visitedKey(),JSON.stringify([...s]));renderChapterProgress()}
function renderChapterProgress(){const phase=effectiveExperimentList(),ids=new Set(phase.map(x=>x.id)),seen=visitedSet(),v=[...seen].filter(id=>ids.has(id)).length,total=phase.length,p=total?Math.min(100,Math.round(v/total*100)):0;setText('chapterProgressText',`${v} / ${total} phase dibuka`);setText('chapterProgressPct',p+'%');$('chapterProgressBar').style.width=p+'%'}
async function loadExperiments(){try{const r=await readRequest('/api/experiments',{timeoutMs:6000}),j=await r.json();if(!r.ok)throw new Error(j.message||`experiments HTTP ${r.status}`);experiments=j;setText('labLeafCount',Object.values(experiments).reduce((n,a)=>n+(a?.length||0),0));setText('navTestCount',(experiments.navigation||[]).length);setText('perTestCount',(experiments.perception||[]).length);setText('escTestCount',(experiments.steering||[]).length);renderExperimentList();if(Object.keys(configs).length)renderConfigBrowser();const list=effectiveExperimentList();if(list.length)selectExperimentById(list[0].id)}catch(e){$('experimentList').innerHTML='<div class="empty-state">Catalog unavailable: '+escapeHtml(e.message)+'</div>'}}
function experimentRole(x){const phase=experimentPhase(x),fields=tuningFieldsFor(x),editable=fields.filter(p=>p.yamlFileKey&&p.kind!=='yaml_readonly'&&!p.locked).length;if(x?.reportMode||phase==='final'||phase==='certification')return'FINAL';if(editable>0)return'TUNE';if((x?.graphCaptions||[]).length>0)return'MEASURE';return'VALIDATE'}
