'use strict';
const $=id=>document.getElementById(id); const q=(s,r=document)=>r.querySelector(s); const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const state={}; let updated={}; let vescTelemetryByMotor={1:{},2:{}}; let serverDelta=0; let sse=null; let lastHmiPage=''; let experiments={}; let configs={}; let uiConfigSchema={version:2,parameters:{}}; let configStateSnapshot={}; let configValidation=null; let currentExp='navigation'; let mapImage=null,globalCostmapImage=null,localCostmapImage=null; let costmapImageAt={global:0,local:0}; let mapView={zoom:1,panX:0,panY:0,tool:'goal',drag:null,draft:null,initialDraft:null,follow:false,measure:{a:null,b:null,preview:null},trail:[],gnssTrail:[],trailMax:1500}; let missionDraft=(()=>{try{return JSON.parse(localStorage.getItem('adv-mission-draft')||'[]')}catch(_){return[]}})(),selectedMissionDraft=-1; const history=[],eventLog=[],eventLast=new Map(); const channelTiming=new Map(), ekfGrowthState=new Map(), scatterOrigins=new Map(), reportDerivedCache=new Map(); let chartEpochMs=Date.now(); let pendingPlanGoalAtMs=0,lastPlanningLatencyMs=NaN; let reportCostmapMetricCache={key:'',minClearance:NaN,valid:NaN};
const STICKY_STREAMS=new Set(['foc_telemetry','vesc_tool_telemetry','vesc_left_values','vesc_right_values','imu','rm3100_mag','rm3100_mag_calibrated','rm3100_heading','imu_inertial_heading','validated_heading','gnss_fix','gnss_quality','gnss_vel','ekf_local','ekf_global','esc_odom']);
let renderQueued=false,lastRenderAt=0,mapDrawQueued=false,mapDrawRaf=0,lastMapDrawAt=0,lastOverviewHealthAt=0;
const PAGE_RENDER_MS={overview:200,navigation:67,'map-editor':67,perception:100,sensors:200,esc:100,'esc-status':125,'esc-ackermann':200,'rm3100-calibration':125,calibration:200,tuning:125,reports:500,diagnostics:250,experiments:125,configuration:500,replay:250};
const uiPerf={renders:0,mapDraws:0,labFast:0,labSlow:0,pageRenders:{}};window.__AGV_UI_PERF=uiPerf;
function activeRenderMs(){return document.hidden?1000:(PAGE_RENDER_MS[activePage]||250)}

const CHANNEL_REGISTRY={
  foc_telemetry:{label:'ESC FOC',expectedHz:50,staleMs:250},
  esc_odom:{label:'ESC Odometry',expectedHz:50,staleMs:250},
  imu:{label:'Yahboom IMU',expectedHz:50,staleMs:250},
  rm3100_mag:{label:'RM3100 Wire',expectedHz:20,staleMs:500},
  rm3100_mag_calibrated:{label:'RM3100 Calibrated',expectedHz:20,staleMs:500},
  rm3100_heading:{label:'RM3100 Heading',expectedHz:20,staleMs:500},
  imu_inertial_heading:{label:'Yaw Inertial',expectedHz:20,staleMs:500},
  validated_heading:{label:'Yaw Validated',expectedHz:10,staleMs:750},
  gnss_fix:{label:'GNSS Fix',expectedHz:10,staleMs:500},
  gnss_quality:{label:'GNSS Quality',expectedHz:10,staleMs:500},
  ekf_local:{label:'EKF Local',expectedHz:10,staleMs:300},
  ekf_global:{label:'EKF Global',expectedHz:10,staleMs:300},
  mppi_status:{label:'MPPI',expectedHz:5,staleMs:600},
  cmd_final:{label:'Final cmd_vel',expectedHz:30,staleMs:300},
  camera_frame:{label:'Camera Frame',expectedHz:5,staleMs:700}
};
let sseLastSeq=null,sseGapCount=0,sseResyncCount=0,sseResyncBusy=false,replayMode=false;
let cameraFrameStore=null;
function elementVisible(el){return !!(el&&!el.hidden&&el.getClientRects().length)}
function cameraGeometryFor(img){return img&&img.naturalWidth&&img.naturalHeight&&window.AGVCameraGeometry?new AGVCameraGeometry({naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight,rect:img.getBoundingClientRect(),mirrorX:true,dpr:window.devicePixelRatio||1}):null}
function initCameraFrameStore(){if(cameraFrameStore||!window.AGVCameraFrameStore)return;cameraFrameStore=new AGVCameraFrameStore({url:'/api/camera.jpg',intervalMs:250,canFetch:()=>!replayMode&&bool(raw('connected.camera'))});cameraFrameStore.subscribe('live',{img:$('cameraImage'),placeholder:$('cameraPlaceholder'),isActive:()=>activePage==='perception'&&elementVisible($('perceptionCameraSection')),onFrame:()=>drawPerceptionDirectOverlay?.()});cameraFrameStore.subscribe('experiment',{img:$('expCameraImage'),placeholder:$('expCameraEmpty'),isActive:()=>activePage==='experiments'&&currentExp==='perception'&&elementVisible($('contextCamera'))});cameraFrameStore.subscribe('obstacle',{img:$('obcalImage'),placeholder:$('obcalCameraEmpty'),isActive:()=>elementVisible($('obstacleCalibrationWizard')),onFrame:()=>{renderObstacleCalibrationLive();drawObstacleCalibrationOverlay()}})}
const deg=r=>Number.isFinite(+r)?+r*180/Math.PI:null; const fmt=(v,n=2,s='--')=>Number.isFinite(+v)?(+v).toFixed(n):s; const bool=v=>v===true; const raw=k=>state[k]; const obj=k=>(state[k]&&typeof state[k]==='object')?state[k]:{};
const textish=o=>{if(o==null)return '--';if(typeof o==='string')return o;if(typeof o==='boolean')return o?'TRUE':'FALSE';if(typeof o==='number')return fmt(o,3);if(o.raw)return String(o.raw);return JSON.stringify(o)};
function pretty(o){if(o==null)return 'No data.'; return typeof o==='string'?o:JSON.stringify(o,null,2)}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function setChip(id,ok,labelOk='READY',labelWait='WAIT'){const e=$(id);if(!e)return;e.classList.remove('waiting','bad'); if(ok===true){e.textContent=labelOk}else if(ok===false){e.textContent=labelWait;e.classList.add('bad')}else{e.textContent=labelWait;e.classList.add('waiting')}}
function age(k){const t=+updated[k];if(!Number.isFinite(t))return Infinity;const serverNow=Date.now()-serverDelta;return Math.max(0,(serverNow-t)/1000)}
function channelFresh(k,sec=3){return age(k)<sec}
function healthCard(name,status,detail){const el=q(`[data-health="${name}"]`);if(!el)return;el.classList.remove('ok','warn','bad');el.classList.add(status);const b=q('b',el),small=q('small',el);if(b)b.textContent=status==='ok'?'ONLINE':status==='warn'?'WAIT':'OFFLINE';if(small&&detail)small.textContent=detail}
function getPath(o,...keys){for(const k of keys){if(o&&o[k]!=null)return o[k]}return null}
function statusRaw(k){const o=obj(k);return o.raw||textish(o)}
function preferredRmMag(){return obj('rm3100_mag')}
function preferredRmChannel(){return 'rm3100_mag'}
function headingValueText(o){return Number.isFinite(+o?.yaw_rad)?`${fmt(deg(o.yaw_rad),1)}°`:'--'}
function magFieldText(o,vector=false){if(!o||!Number.isFinite(+o.norm_ut))return'--';return vector?`${fmt(o.x_ut,1)}, ${fmt(o.y_ut,1)}, ${fmt(o.z_ut,1)} µT | ${fmt(o.norm_ut,1)} µT`:`${fmt(o.norm_ut,1)} µT`}
function ekfPoseText(o){if(!o||!Number.isFinite(+o.x))return'--';return `${fmt(o.x,2)}, ${fmt(o.y,2)}, ${fmt(o.z,2)} m | ${fmt(deg(o.yaw),1)}°`}
function ekfTwistText(o){if(!o||!Number.isFinite(+(o.vx??o.v)))return'--';return `${fmt(o.vx??o.v,2)}, ${fmt(o.vy,2)}, ${fmt(o.wz??o.w,3)}`}
function ekfSigmaText(o){if(!o)return'--';const sx=Number.isFinite(+o.var_x)&&+o.var_x>=0?Math.sqrt(+o.var_x):NaN,sy=Number.isFinite(+o.var_y)&&+o.var_y>=0?Math.sqrt(+o.var_y):NaN,syaw=Number.isFinite(+o.var_yaw)&&+o.var_yaw>=0?deg(Math.sqrt(+o.var_yaw)):NaN;if(![sx,sy,syaw].some(Number.isFinite))return'--';return `${fmt(sx,3)} / ${fmt(sy,3)} m / ${fmt(syaw,2)}°`}
function streamHealthText(k){const r=channelRate(k),a=age(k);return `${Number.isFinite(r)?r.toFixed(1)+' Hz':'--'} / ${Number.isFinite(a)?(a*1000).toFixed(0)+' ms':'--'}`}
function renderHeadingEkfSummary(prefix){
  const rm=obj('rm3100_mag'),rmCal=obj('rm3100_mag_calibrated'),rmHeading=obj('rm3100_heading'),inertial=obj('imu_inertial_heading'),validated=obj('validated_heading'),status=obj('magnetic_heading_status'),local=obj('ekf_local'),global=obj('ekf_global');
  const vector=prefix==='nav',rmLive=channelFresh('rm3100_mag',1.5)&&bool(raw('connected.rm3100')),headingLive=channelFresh('rm3100_heading',1.5),validatedLive=channelFresh('validated_heading',1.5);
  setText(prefix+'RmField',magFieldText(rm,vector));const calFieldText=magFieldText(rmCal,vector);setText(prefix+'RmCalField',calFieldText==='--'?'WAIT FULL-3D':calFieldText);setText(prefix+'RmHeading',headingValueText(rmHeading));
  setText(prefix+'InertialHeading',headingValueText(inertial));setText(prefix+'ValidatedHeading',headingValueText(validated));
  const owner=String(status.cal_owner??'--'),full=status.rm3100_full3d===true,planar=status.rm3100_planar===true,lut=status.rm3100_lut===true;
  setText(prefix+'HeadingCalibration',`${owner.toUpperCase()} • ${full?'FULL 3D':planar?'PLANAR':'WIRE'}${lut?' + LUT':''}`);
  setText(prefix+'HeadingSource','NEO3 PRO RM3100');
  if(prefix==='nav')setText('navMapYawOffset',Number.isFinite(+raw('map_yaw_from_enu'))?`${fmt(deg(raw('map_yaw_from_enu')),1)}°`:'--');
  setChip(prefix+'HeadingChip',rmLive&&headingLive&&validatedLive,'RM3100 LIVE','WAIT RM3100');
  setText(prefix+'EkfLocalPose',ekfPoseText(local));setText(prefix+'EkfLocalTwist',ekfTwistText(local));setText(prefix+'EkfLocalCov',ekfSigmaText(local));setText(prefix+'EkfLocalHealth',streamHealthText('ekf_local'));
  setText(prefix+'EkfGlobalPose',ekfPoseText(global));setText(prefix+'EkfGlobalTwist',ekfTwistText(global));setText(prefix+'EkfGlobalCov',ekfSigmaText(global));setText(prefix+'EkfGlobalHealth',streamHealthText('ekf_global'));
  setChip(prefix+'EkfChip',channelFresh('ekf_local',1)&&channelFresh('ekf_global',1),'BOTH LIVE','WAIT');
}
function pageName(p){return {overview:['SYSTEM MONITOR','Overview'],'map-editor':['MAP ENGINEERING','Map Editor'],replay:['LOG ANALYSIS','Replay'],navigation:['NAV2 WORKSPACE','Map & Mission'],perception:['VISION SYSTEM','Perception Live'],sensors:['LOCALIZATION INPUT','GNSS & IMU'],esc:['ACTUATION','ESC Motor Workbench'],'esc-status':['ACTUATION STATUS','ESC Status'],'esc-ackermann':['ACTUATION','Ackermann Scaling'],calibration:['COMMISSIONING','Calibration'],'rm3100-calibration':['NAVIGATION SENSOR','RM3100 Calibration'],tuning:['CONTROL LOOP','Live Control'],experiments:['CONTROL ENGINEERING','Tuning & Control'],reports:['EVIDENCE','Reports & Export'],diagnostics:['ENGINEERING','Diagnostics'],configuration:['SYSTEM SOURCE','Configuration']}[p]||['SYSTEM','Dashboard']}
const GLOBAL_TOOLS=[['configuration','Configuration','☷'],['diagnostics','Diagnostics','⌁'],['replay','Replay / Log Analysis','▶'],['reports','Reports & Export','⇩']];
const DOMAIN_MENU={
  overview:{label:'SYSTEM',title:'Overview',defaultPage:'overview',items:[['overview','Overview','◫'],...GLOBAL_TOOLS]},
  navigation:{label:'NAVIGATION',title:'Navigasi',defaultPage:'navigation',exp:'navigation',items:[['navigation','Nav2 & Mission','⌖'],['sensors','GNSS / IMU','G'],['rm3100-calibration','Kalibrasi RM3100','⊙'],['calibration','Kalibrasi Sensor','◎']],tools:GLOBAL_TOOLS},
  map:{label:'MAP',title:'Map',defaultPage:'map-editor',items:[['map-editor','Map Editor','▦']],tools:GLOBAL_TOOLS},
  perception:{label:'PERCEPTION',title:'Persepsi',defaultPage:'perception',exp:'perception',items:[['perception','Persepsi Live & Safety','◉']],tools:GLOBAL_TOOLS},
  esc:{label:'ESC',title:'ESC',defaultPage:'esc-status',exp:'steering',items:[['esc-status','ESC Status','●'],['esc','ESC Motor Workbench','⚙'],['esc-ackermann','Ackermann Scaling','↔']],tools:GLOBAL_TOOLS}
};

// Firda thesis acquisition view. This is an additional pink steering-only index
// layered on top of the existing yellow ESC/BAB-IV tree; existing experiment
// IDs remain the source of truth for recorders, graphs, qualification and export.
const FIRDA_ESC_REPORT_MENU=[
  {group:'4.1 KALIBRASI STEERING',items:[
    {id:'4.1.1',title:'Zero Current & Vbus',target:'4.2.2',hint:'stationary • LEFT steering • 3 run'},
    {id:'4.1.2',title:'Encoder ABI TIM4',target:'4.2.3',hint:'LEFT → CENTER → RIGHT → CENTER'},
    {id:'4.1.3',title:'Center Steering',target:'4.2.3',hint:'center repeatability • 5×'},
    {id:'4.1.4',title:'Batas Kiri–Tengah–Kanan',target:'4.2.3',hint:'endpoint calibration • dynamic limit ±28°'},
    {id:'4.1.5',title:'R / L / Flux Linkage',page:'esc',pane:'tune',anchor:'vescMotorSetupSection',hint:'Workbench Maintenance • LEFT steering'},
    {id:'4.1.6',title:'Sudut Elektrik FOC',target:'4.2.4',hint:'Id/Iq • Vd/Vq • theta offset'}
  ]},
  {group:'4.2 TUNING FOC STEERING',items:[
    {id:'4.2.1',title:'Tuning Kp Arus',target:'4.3.1',hint:'0.5× / 1.0× / 1.5× baseline • screen 1.0 A'},
    {id:'4.2.2',title:'Tuning Ki Arus',target:'4.3.1',hint:'Kp terpilih dikunci • OFAT Ki'},
    {id:'4.2.3',title:'Validasi PI Arus',target:'4.3.1',hint:'0.5 A • 1.0 A • 1.5 A • 3× repeat'}
  ]},
  {group:'4.3 TUNING POSISI STEERING',items:[
    {id:'4.3.1',title:'Tuning Kp Posisi',target:'4.4.1',hint:'0.0125 • 0.0250 • 0.0375 • screen ±5°'},
    {id:'4.3.2',title:'Tuning Ki Posisi',target:'4.4.1',hint:'hanya jika steady-state error masih perlu dikoreksi'},
    {id:'4.3.3',title:'Tuning Kd Posisi',target:'4.4.1',hint:'hanya jika damping tambahan dibutuhkan'},
    {id:'4.3.4',title:'Validasi Gain Final',target:'4.4.1',hint:'lock FOC + position sebelum uji lapangan'}
  ]},
  {group:'4.4 VALIDASI RESPONS',items:[
    {id:'4.4.1',title:'Step ±10°',target:'4.5.1',hint:'LEFT steering • 3× per arah'},
    {id:'4.4.2',title:'Step ±20°',target:'4.5.1',hint:'LEFT steering • 3× per arah'},
    {id:'4.4.3',title:'Repeatability',target:'4.6.2',hint:'LEFT → CENTER → RIGHT → CENTER • 5 siklus'},
    {id:'4.4.4',title:'Simetri Kiri / Kanan',target:'4.6.1',hint:'bandingkan −10/+10 dan −20/+20'}
  ]},
  {group:'4.5 UJI BEBAN STEERING',items:[
    {id:'4.5.1',title:'Beban 0 Galon',target:'4.8.1',hint:'−20° • 0° • +20° • 3× repeat'},
    {id:'4.5.2',title:'Beban 1 Galon',target:'4.8.1',hint:'−20° • 0° • +20° • 3× repeat'},
    {id:'4.5.3',title:'Beban 2 Galon',target:'4.8.1',hint:'−20° • 0° • +20° • 3× repeat'},
    {id:'4.5.4',title:'Beban 3 Galon',target:'4.8.1',hint:'−20° • 0° • +20° • 3× repeat'}
  ]},
  {group:'4.6 HASIL AKHIR',items:[
    {id:'4.6.1',title:'Rekap Parameter Final',target:'4.9',hint:'FOC • position • limits • persistence'},
    {id:'4.6.2',title:'Ringkasan Kinerja',target:'4.10',hint:'target/actual • RMSE • settling • current'},
    {id:'4.6.3',title:'Evidence Checklist',target:'4.11',hint:'data aktual • qualification • no dummy/estimasi'}
  ]},
  {group:'4.7 EXPORT DATA',items:[
    {id:'4.7.1',title:'CSV / XLSX / PNG',target:'4.11',hint:'export evidence untuk BAB IV Firda'}
  ]}
];
let activeFirdaEscStep='';
function firdaEscItems(){return FIRDA_ESC_REPORT_MENU.flatMap(g=>g.items)}
function firdaEscOverlay(step,source){
  const x={...source,liveSeries:{...(source?.liveSeries||{})},graphs:(source?.graphs||[]).map(g=>({...g,series:[...(g.series||[])]})),tableColumns:(source?.tableColumns||[]).map(a=>[...a]),tableNames:[...(source?.tableNames||[])],graphCaptions:[...(source?.graphCaptions||[])]};
  x.firdaId=step.id;x.firdaTitle=step.title;x.groupTitle=FIRDA_ESC_REPORT_MENU.find(g=>g.items.some(i=>i.id===step.id))?.group||'DATA LAPORAN FIRDA';x.section=`${step.id} ${step.title}`;
  const set=(cols,live,graphs=[])=>{x.tableColumns=[cols];x.tableNames=['Data Aktual Steering LEFT'];x.liveSeries=live;x.graphs=graphs;x.graphCaptions=graphs.map(g=>g.caption||'Data aktual')};
  const L={motor:'foc_telemetry.left.current_motor_a',input:'foc_telemetry.left.current_in_a',vbus:'foc_telemetry.left.vbus_v',id:'foc_telemetry.left.id_a',iq:'foc_telemetry.left.iq_a',duty:'foc_telemetry.left.duty',pos:'foc_telemetry.left.position_deg',fault:'foc_telemetry.left.fault',raw:'foc_telemetry.steering_cal.raw_now'};
  if(step.id==='4.1.1')set(['Variasi','LEFT Motor Current','LEFT Input Current','LEFT Id','LEFT Iq','LEFT Vbus','LEFT Fault','Status'],{'LEFT Motor Current':L.motor,'LEFT Input Current':L.input,'LEFT Id':L.id,'LEFT Iq':L.iq,'LEFT Vbus':L.vbus,'LEFT Fault':L.fault},[{type:'time_series',series:['LEFT Motor Current','LEFT Input Current'],xLabel:'Time [s]',yLabel:'Current [A]',caption:'Arus nol steering LEFT'},{type:'time_series',series:['LEFT Id','LEFT Iq'],xLabel:'Time [s]',yLabel:'Current [A]',caption:'Id / Iq saat zero-current'},{type:'time_series',series:['LEFT Vbus'],xLabel:'Time [s]',yLabel:'V',caption:'Vbus steering LEFT'}]);
  else if(step.id==='4.1.2')set(['Variasi','Raw TIM4','LEFT Position','Raw Center','Raw Left','Raw Right','Encoder Synced','Status'],{'Raw TIM4':L.raw,'LEFT Position':L.pos,'Raw Center':'foc_telemetry.steering_cal.raw_center','Raw Left':'foc_telemetry.steering_cal.raw_left','Raw Right':'foc_telemetry.steering_cal.raw_right','Encoder Synced':'foc_telemetry.steering_cal.encoder_synced'},[{type:'time_series',series:['Raw TIM4','LEFT Position'],xLabel:'Time [s]',yLabel:'count / deg',caption:'Encoder ABI TIM4'}]);
  else if(step.id==='4.1.3')set(['Variasi','Raw TIM4','Raw Center','LEFT Position','Physical Center','Encoder Synced','Homed','Status'],{'Raw TIM4':L.raw,'Raw Center':'foc_telemetry.steering_cal.raw_center','LEFT Position':L.pos,'Physical Center':'foc_telemetry.steering_cal.physical_center_deg','Encoder Synced':'foc_telemetry.steering_cal.encoder_synced','Homed':'foc_telemetry.steering_cal.homed'},[{type:'time_series',series:['Raw TIM4','LEFT Position'],xLabel:'Time [s]',yLabel:'count / deg',caption:'Repeatability center'}]);
  else if(step.id==='4.1.4')set(['Variasi','Raw TIM4','Raw Left','Raw Center','Raw Right','Physical Min','Physical Max','LEFT Position','Status'],{'Raw TIM4':L.raw,'Raw Left':'foc_telemetry.steering_cal.raw_left','Raw Center':'foc_telemetry.steering_cal.raw_center','Raw Right':'foc_telemetry.steering_cal.raw_right','Physical Min':'foc_telemetry.steering_cal.physical_min_deg','Physical Max':'foc_telemetry.steering_cal.physical_max_deg','LEFT Position':L.pos},[{type:'time_series',series:['Raw TIM4','LEFT Position'],xLabel:'Time [s]',yLabel:'count / deg',caption:'Batas steering'}]);
  else if(step.id==='4.1.6')set(['Variasi','LEFT Id','LEFT Iq','LEFT Position','Raw TIM4','Encoder Synced','Homed','Status'],{'LEFT Id':L.id,'LEFT Iq':L.iq,'LEFT Position':L.pos,'Raw TIM4':L.raw,'Encoder Synced':'foc_telemetry.steering_cal.encoder_synced','Homed':'foc_telemetry.steering_cal.homed'},[{type:'time_series',series:['LEFT Id','LEFT Iq'],xLabel:'Time [s]',yLabel:'Current [A]',caption:'Alignment Id/Iq'},{type:'time_series',series:['LEFT Position','Raw TIM4'],xLabel:'Time [s]',yLabel:'deg / count',caption:'Posisi dan encoder'}]);
  else if(/^4\.2\./.test(step.id))set(['Variasi','LEFT Id','LEFT Iq','LEFT Motor Current','LEFT Duty','LEFT Vbus','Status'],{'LEFT Id':L.id,'LEFT Iq':L.iq,'LEFT Motor Current':L.motor,'LEFT Duty':L.duty,'LEFT Vbus':L.vbus},[{type:'time_series',series:['LEFT Iq','LEFT Motor Current'],xLabel:'Time [s]',yLabel:'A',caption:'Respons arus FOC'},{type:'time_series',series:['LEFT Id'],xLabel:'Time [s]',yLabel:'A',caption:'Id terhadap waktu'},{type:'time_series',series:['LEFT Duty','LEFT Vbus'],xLabel:'Time [s]',yLabel:'duty / V',caption:'Duty dan Vbus'}]);
  else if(/^4\.3\./.test(step.id))set(['Variasi','Steering Target','Steering Actual','Steering Error','LEFT Iq','LEFT Motor Current','LEFT Duty','Status'],{'Steering Target':'esc_steer_target','Steering Actual':'esc_steer_actual','Steering Error':'derived.steering_error_rad','LEFT Iq':L.iq,'LEFT Motor Current':L.motor,'LEFT Duty':L.duty},[{type:'time_series',series:['Steering Target','Steering Actual'],xLabel:'Time [s]',yLabel:'rad',caption:'Target dan aktual posisi'},{type:'time_series',series:['Steering Error','LEFT Iq'],xLabel:'Time [s]',yLabel:'error / A',caption:'Error dan Iq'}]);
  else if(/^4\.4\./.test(step.id))set(['Variasi','Steering Target','Steering Actual','Steering Error','Raw TIM4','LEFT Iq','LEFT Motor Current','LEFT Duty','Status'],{'Steering Target':'esc_steer_target','Steering Actual':'esc_steer_actual','Steering Error':'derived.steering_error_rad','Raw TIM4':L.raw,'LEFT Iq':L.iq,'LEFT Motor Current':L.motor,'LEFT Duty':L.duty},[{type:'time_series',series:['Steering Target','Steering Actual'],xLabel:'Time [s]',yLabel:'rad',caption:'Respons steering'},{type:'time_series',series:['Steering Error'],xLabel:'Time [s]',yLabel:'rad',caption:'Error steering'},{type:'time_series',series:['LEFT Iq','LEFT Motor Current'],xLabel:'Time [s]',yLabel:'A',caption:'Arus saat respons'}]);
  else if(/^4\.5\./.test(step.id))set(['Kondisi','Steering Target','Steering Actual','Steering Error','LEFT Iq','LEFT Motor Current','LEFT Input Current','LEFT Duty','LEFT Vbus','Status'],{'Steering Target':'esc_steer_target','Steering Actual':'esc_steer_actual','Steering Error':'derived.steering_error_rad','LEFT Iq':L.iq,'LEFT Motor Current':L.motor,'LEFT Input Current':L.input,'LEFT Duty':L.duty,'LEFT Vbus':L.vbus},[{type:'time_series',series:['Steering Target','Steering Actual'],xLabel:'Time [s]',yLabel:'rad',caption:'Posisi steering berbeban'},{type:'time_series',series:['Steering Error'],xLabel:'Time [s]',yLabel:'rad',caption:'Error berbeban'},{type:'time_series',series:['LEFT Iq','LEFT Motor Current','LEFT Input Current'],xLabel:'Time [s]',yLabel:'A',caption:'Arus berbeban'},{type:'time_series',series:['LEFT Duty','LEFT Vbus'],xLabel:'Time [s]',yLabel:'duty / V',caption:'Duty dan Vbus'}]);
  return x;
}
function openFirdaEscStep(id){
  const step=firdaEscItems().find(x=>x.id===id);if(!step)return;
  activeFirdaEscStep=id;
  if(step.target){openDomainTuning(step.target,'firda');if(selectedExperiment){selectedExperiment=firdaEscOverlay(step,selectedExperiment);renderSelectedExperiment();renderContextNav()}return}
  if(step.page){
    activeDomain='esc';activatePage(step.page,false,'esc');
    if(step.page==='esc'&&step.pane&&WORKSPACE_PANES.esc?.[step.pane]){activeWorkspaceTab.esc=step.pane;setWorkspacePaneVisibility('esc',step.pane);renderWorkspaceTabs()}
    requestAnimationFrame(()=>document.getElementById(step.anchor)?.scrollIntoView({behavior:'smooth',block:'start'}));
  }
}
const WORKSPACE_TABS={
  overview:[['monitor','Monitor','pane:overview:monitor'],['health','Health','pane:overview:health'],['authority','Authority','pane:overview:authority'],['events','Events / Alerts','pane:overview:events'],['configuration','Parameters','page:configuration'],['diagnostics','Diagnostics','page:diagnostics'],['replay','Replay','page:replay'],['reports','Reports','page:reports']],
  esc:[['status','Status','page:esc-status'],['live','Live','pane:esc:live'],['control','Control','pane:esc:control'],['tune','Tune','pane:esc:tune'],['analysis','Analysis','pane:esc:diagnostics'],['utilities','Utility / Terminal','pane:esc:utilities'],['ackermann','Ackermann','page:esc-ackermann'],['bab4','BAB IV Data','exp:steering:4.1'],['params','Parameters','page:configuration'],['replay','Replay','page:replay'],['tests','Tests','page:experiments']],
  navigation:[['map','Map / Mission','page:navigation'],['sensors','Sensors','page:sensors'],['rm3100','RM3100 Cal','page:rm3100-calibration'],['localization','Localization','navpane:ekf-global'],['planner','Planner','navpane:planner'],['controller','Controller','navpane:mppi'],['safety','Safety','navpane:safety'],['bab4','BAB IV Data','report:R4.1.1'],['tune','Tune','page:experiments'],['params','Parameters','page:configuration'],['diagnostics','Diagnostics','page:diagnostics'],['replay','Replay','page:replay'],['reports','Reports','page:reports']],
  perception:[['live','Live','pane:perception:live'],['detection','Detection','pane:perception:detection'],['lane','Lane','pane:perception:lane'],['planning','Planning','pane:perception:planning'],['safety','Safety','pane:perception:safety'],['calibration','Calibration','pane:perception:calibration'],['performance','Performance','pane:perception:performance'],['evidence','Evidence','pane:perception:evidence'],['bab4','BAB IV Data','exp:perception:F4.1'],['tune','Tune','page:experiments'],['params','Parameters','page:configuration'],['diagnostics','Diagnostics','page:diagnostics'],['replay','Replay','page:replay']]
};
const WORKSPACE_PANES={
  overview:{monitor:['#page-overview .hero-grid'],health:['#overviewHealthSection','#page-overview .health-grid','#overviewDataHealthSection','#page-overview .data-health-panel'],authority:['#overviewAuthoritySection','#page-overview .authority-panel','#overviewPipelineSection'],events:['#overviewAlertsSection']},
  esc:{live:['#vescGraphSection','#vescLiveSection','#vescRotorSection'],control:['#vescControlSection','#vescDriveScaleSection'],tune:['#vescTuningSection','#vescLimitsSection','#vescConfigSection','#vescEncoderSection'],diagnostics:['#vescCompareSection','#vescFaultSection'],utilities:['#vescUtilitySection']},
  perception:{live:['#perceptionCameraSection'],detection:['#perceptionCameraSection','#perceptionDetectionsSection'],lane:['#perceptionCameraSection','#perceptionLaneSection'],planning:['#perceptionPlanningSection'],safety:['#perceptionSafetySection'],calibration:['#perceptionCameraSection','#perceptionCalibrationSection'],performance:['#perceptionPerformanceSection'],evidence:['#perceptionEvidenceSection']}
};
const WORKSPACE_CONTAINERS=['#perceptionCameraLayout','#perceptionAnalysisRow','#page-overview .two-col'];
let activeWorkspaceTab={overview:'monitor',esc:'status',navigation:'map',perception:'live'};
const paneFocusMemory=new WeakMap();
function setPaneAccessible(el,visible){if(!el)return;el.classList.add('workspace-pane');el.hidden=!visible;el.setAttribute('aria-hidden',String(!visible));for(const node of qa('a,button,input,select,textarea,[tabindex]',el)){if(!visible){if(!paneFocusMemory.has(node))paneFocusMemory.set(node,node.getAttribute('tabindex'));node.tabIndex=-1}else if(paneFocusMemory.has(node)){const old=paneFocusMemory.get(node);old===null?node.removeAttribute('tabindex'):node.setAttribute('tabindex',old);paneFocusMemory.delete(node)}}}
function setupWorkspacePanes(){for(const panes of Object.values(WORKSPACE_PANES))for(const selectors of Object.values(panes))for(const selector of selectors)for(const el of qa(selector))el.classList.add('workspace-pane')}
function refreshWorkspaceContainers(){for(const selector of WORKSPACE_CONTAINERS)for(const box of qa(selector)){const members=qa('.workspace-pane',box);box.classList.toggle('workspace-container-empty',members.length>0&&!members.some(x=>!x.hidden))}}
function setWorkspacePaneVisibility(page,pane){const panes=WORKSPACE_PANES[page];if(!panes)return;const visible=new Set(panes[pane]||[]);const all=new Set(Object.values(panes).flat());for(const selector of all)for(const el of qa(selector))setPaneAccessible(el,visible.has(selector));refreshWorkspaceContainers()}
function clearWorkspacePaneVisibility(page){const panes=WORKSPACE_PANES[page];if(!panes)return;for(const selector of new Set(Object.values(panes).flat()))for(const el of qa(selector))setPaneAccessible(el,true);refreshWorkspaceContainers()}
function bindHorizontalTabKeys(box,selector,activate){if(!box)return;const items=qa(selector,box);items.forEach((b,i)=>{b.setAttribute('role','tab');b.setAttribute('aria-selected',String(b.classList.contains('active')));b.tabIndex=b.classList.contains('active')?0:-1;b.onkeydown=e=>{let n=null;if(e.key==='ArrowRight')n=(i+1)%items.length;else if(e.key==='ArrowLeft')n=(i-1+items.length)%items.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=items.length-1;if(n===null)return;e.preventDefault();items[n].focus();activate(items[n])}});const a=items.find(x=>x.classList.contains('active'));a?.scrollIntoView({block:'nearest',inline:'nearest'})}
function workspaceControlId(action){if(action.startsWith('pane:'))return `page-${action.split(':')[1]}`;if(action.startsWith('page:'))return `page-${action.slice(5)}`;if(action.startsWith('navpane:'))return `navInspectorPane-${action.slice(8)}`;return ''}
function renderWorkspaceTabs(){const box=$('workspaceTabs');if(!box)return;const tabs=WORKSPACE_TABS[activeDomain]||[];if(!tabs.length){box.innerHTML='';box.hidden=true;box.setAttribute('aria-hidden','true');return}const active=activeWorkspaceTab[activeDomain]||tabs[0][0];box.hidden=false;box.setAttribute('aria-hidden','false');box.innerHTML=tabs.map(([id,label,action])=>`<button type="button" class="workspace-tab ${id===active?'active':''}" data-workspace-tab="${escapeHtml(id)}" data-workspace-action="${escapeHtml(action||'')}">${escapeHtml(label)}</button>`).join('');const activate=b=>activateWorkspaceTab(b.dataset.workspaceTab);qa('[data-workspace-tab]',box).forEach(b=>b.onclick=()=>activate(b));bindHorizontalTabKeys(box,'[data-workspace-tab]',activate)}
function activateWorkspaceTab(id){const tabs=WORKSPACE_TABS[activeDomain]||[],t=tabs.find(x=>x[0]===id);if(!t)return;activeWorkspaceTab[activeDomain]=id;const action=t[2]||'';if(action.startsWith('pane:')){const [,page,pane]=action.split(':');activatePage(page,false,activeDomain);if(WORKSPACE_PANES[page])setWorkspacePaneVisibility(page,pane);renderWorkspaceTabs();return}if(action.startsWith('page:')){const page=action.slice(5);activatePage(page,true,activeDomain);if(WORKSPACE_PANES[page])clearWorkspacePaneVisibility(page);renderWorkspaceTabs();return}if(action.startsWith('navpane:')){activatePage('navigation',false,'navigation');const pane=action.slice(8);requestAnimationFrame(()=>{const b=q(`[data-nav-inspector="${pane}"]`);if(b)b.click();const d=$('navInspector');if(d)d.open=true});renderWorkspaceTabs();return}if(action.startsWith('report:')){openNavigationReport(action.slice(7));renderWorkspaceTabs();return}if(action.startsWith('exp:')){const [,domain,id0]=action.split(':');if(domain==='steering')activeDomain='esc';else if(domain==='perception')activeDomain='perception';currentExp=domain;openDomainTuning(id0);renderWorkspaceTabs();return}}
function syncWorkspaceTabFromPage(page){const tabs=WORKSPACE_TABS[activeDomain]||[],cur=tabs.find(x=>x[0]===activeWorkspaceTab[activeDomain]),a=cur?.[2]||'';const currentStillMatches=a===`page:${page}`||a.startsWith(`pane:${page}:`)||(page==='navigation'&&a.startsWith('navpane:'))||(page==='experiments'&&a==='page:experiments');if(currentStillMatches)return;const match=tabs.find(x=>x[2]===`page:${page}`||x[2]?.startsWith(`pane:${page}:`));if(match)activeWorkspaceTab[activeDomain]=match[0]}
let activeDomain='overview',activePage='overview';
function domainForPage(page){if(page==='map-editor')return'map';if(page==='navigation'||page==='sensors'||page==='rm3100-calibration'||page==='calibration'||page==='tuning')return'navigation';if(page==='perception')return'perception';if(page==='esc'||page==='esc-status'||page==='esc-ackermann')return'esc';if(page==='experiments')return activeDomain;return'overview'}
function syncExperimentDomain(){const exp=DOMAIN_MENU[activeDomain]?.exp;if(!exp)return;if(currentExp===exp&&selectedExperiment&&effectiveExperimentList().some(x=>x.id===selectedExperiment.id))return;currentExp=exp;selectedExperiment=null;metricHistory.clear();scatterHistory.clear();scatterOrigins.clear();ekfGrowthState.clear();renderExperimentList();const list=effectiveExperimentList();if(list.length)selectExperimentById(list[0].id)}
function renderContextNav(){
  const d=DOMAIN_MENU[activeDomain]||DOMAIN_MENU.overview;
  setText('contextDomainLabel',d.label);setText('contextDomainTitle',d.title);
  const primary=d.items||[],tools=d.tools||[];
  let html=primary.map(([page,label,icon])=>`<button class="nav-item ${page===activePage?'active':''}" data-page="${page}"><span>${icon}</span><b>${label}</b></button>`).join('');
  if(d.exp){
    const list=effectiveExperimentList().filter(x=>!(activeDomain==='navigation'&&x.reportMode===true));let lastGroup='';
    if(activeDomain==='perception'){html+=`<button class="nav-item tuning-nav obcal-shortcut ${activePage==='experiments'&&selectedExperiment?.id==='4.3.1'?'active':''}" data-exp-id="4.3.1"><span>CAL</span><div><b>Kalibrasi Obstacle 1–5 m</b><small>Human + Motorcycle • preview YOLO • CSV + grafik</small></div></button>`;}
    const listHeading=activeDomain==='navigation'?'COMMISSIONING':activeDomain==='perception'?'COMMISSIONING + BAB IV':'BAB IV / TUNING';html+=`<div class="sidebar-tuning-head"><span>${listHeading}</span><small>${list.length} tahap</small></div>`;
    for(const x of list){const group=displayExperimentGroup(x),id=displayExperimentId(x),title=displayExperimentTitle(x);if(group!==lastGroup){html+=`<div class="sidebar-tuning-group">${escapeHtml(group)}</div>`;lastGroup=group}const active=activePage==='experiments'&&selectedExperiment?.id===x.id;html+=`<button class="nav-item tuning-nav ${active?'active':''}" data-exp-id="${escapeHtml(x.id)}"><span>${escapeHtml(id)}</span><div><b>${escapeHtml(title)}</b><small><em class="test-role role-${experimentRole(x).toLowerCase()}">${experimentRole(x)}</em> ${(x.tableNames||[]).length} tabel • ${(x.graphCaptions||[]).length} grafik • ${tuningFieldsFor(x).filter(p=>p.yamlFileKey).length} parameter</small></div></button>`}
    if(activeDomain==='navigation'){
      const reports=navigationReportList();let reportGroup='';
      html+=`<div class="sidebar-report-head"><span>LAPORAN BAB IV</span><small>${reports.length} subjudul</small></div>`;
      for(const x of reports){const group=displayExperimentGroup(x),id=displayExperimentId(x),title=displayExperimentTitle(x);if(group!==reportGroup){html+=`<div class="sidebar-report-group">${escapeHtml(group)}</div>`;reportGroup=group}const active=activePage==='experiments'&&selectedExperiment?.id===x.id;html+=`<button class="nav-item report-nav ${active?'active':''}" data-report-id="${escapeHtml(x.id)}"><span>${escapeHtml(id)}</span><div><b>${escapeHtml(title)}</b><small>START/STOP • Excel • YAML tuning • rekap laporan</small></div></button>`}
    }
    if(activeDomain==='esc'){
      const firda=firdaEscItems();
      html+=`<div class="sidebar-firda-head"><span>DATA LAPORAN FIRDA</span><small>${firda.length} pengujian steering</small></div>`;
      for(const section of FIRDA_ESC_REPORT_MENU){html+=`<div class="sidebar-firda-group">${escapeHtml(section.group)}</div>`;for(const item of section.items){const active=activeFirdaEscStep===item.id;html+=`<button class="nav-item firda-nav ${active?'active':''}" data-firda-id="${escapeHtml(item.id)}" title="${escapeHtml(item.title+' — '+(item.hint||'Steering LEFT'))}"><span>${escapeHtml(item.id)}</span><div><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.hint||'Steering LEFT')}</small></div></button>`}}
    }
    if(tools.length){html+=`<div class="sidebar-tuning-head sidebar-tools-head"><span>TOOLS</span><small>operasional</small></div>`;html+=tools.map(([page,label,icon])=>`<button class="nav-item ${page===activePage?'active':''}" data-page="${page}"><span>${icon}</span><b>${label}</b></button>`).join('')}
  }
  $('contextNav').innerHTML=html;
  qa('.nav-item[data-page]',$('contextNav')).forEach(b=>b.onclick=()=>activatePage(b.dataset.page,true,activeDomain));
  qa('.tuning-nav',$('contextNav')).forEach(b=>b.onclick=()=>openDomainTuning(b.dataset.expId));
  qa('.report-nav',$('contextNav')).forEach(b=>b.onclick=()=>openNavigationReport(b.dataset.reportId));
  qa('.firda-nav',$('contextNav')).forEach(b=>b.onclick=()=>openFirdaEscStep(b.dataset.firdaId));
  window.navigationTuningPolicy?.decorateSidebar?.($('contextNav'));
  qa('.top-domain').forEach(b=>b.classList.toggle('active',b.dataset.domain===activeDomain));renderWorkspaceTabs()
}
function openDomainTuning(id,source='standard'){if(source!=='firda')activeFirdaEscStep='';const d=DOMAIN_MENU[activeDomain];if(!d?.exp)return;currentExp=d.exp;const x=(experiments[currentExp]||[]).find(v=>v.id===id);if(!x)return;activePage='experiments';qa('.page').forEach(v=>v.classList.remove('active'));$('page-experiments').classList.add('active');const [e,t]=pageName('experiments');setText('pageEyebrow',e);setText('pageTitle',t);selectExperimentById(id);renderContextNav();$('sidebar').classList.remove('open')}
function openNavigationReport(id){if(activeDomain!=='navigation')activeDomain='navigation';currentExp='navigation';const x=navigationReportList().find(v=>v.id===id);if(!x)return toast('Subjudul laporan belum tersedia dari source navigasi',true);activePage='experiments';qa('.page').forEach(v=>v.classList.remove('active'));$('page-experiments').classList.add('active');if(typeof setTuningMode==='function')setTuningMode('analyze');selectExperimentById(id);renderContextNav();$('sidebar').classList.remove('open')}
const webToHmiPage={overview:'OVERVIEW',navigation:'NAVIGATION',perception:'PERCEPTION',sensors:'NAVIGATION',esc:'ESC'};function hmiPageToWebPage(page){page=String(page||'').toUpperCase();if(page==='OVERVIEW')return'overview';if(page.startsWith('ESC'))return'esc';if(page.startsWith('PERCEPTION'))return'perception';if(page.startsWith('NAV'))return'navigation';return null;}
let lastUiPageChangeMs=0;let perceptionInferenceUiState=null;async function requestPerceptionInference(enabled){enabled=!!enabled;const b=$('yoloToggleBtn');if(b){b.disabled=true;b.textContent=enabled?'Mengaktifkan YOLOPv2...':'Menonaktifkan YOLOPv2...'}try{const j=await post('/api/perception/inference',{enabled},false);if(j?.ok){perceptionInferenceUiState=enabled;setTimeout(fullState,250)}return j}finally{if(b)b.disabled=false}}async function requestPerceptionSafetyBypass(enabled){enabled=!!enabled;const id='trajectory_safety:trajectory_safety_supervisor.ros__parameters.commissioning_bypass_enabled';const b=$('perceptionSafetyBypassBtn');if(b)b.disabled=true;try{if(!stageConfigChange('trajectory_safety','trajectory_safety_supervisor.ros__parameters.commissioning_bypass_enabled',enabled,{name:'Commissioning safety bypass',source:'perception-safety'}))return null;const item=configPending.get(id);if(item){const j=await validateConfigItems([item]);toast('Safety bypass hanya STAGED + VALIDATED; review diff lalu Apply eksplisit.');return j}return {ok:true,staged:false}}catch(e){toast('Stage safety bypass gagal: '+e.message,true);return null}finally{if(b)b.disabled=false}}function activatePage(page,syncHmi=false,domainOverride=null,source='ui'){if(source!=='hmi')lastUiPageChangeMs=Date.now();const section=$(`page-${page}`);if(!section)return;if(activePage==='navigation'&&page!=='navigation'&&typeof cancelMapDraw==='function')cancelMapDraw();if(domainOverride&&DOMAIN_MENU[domainOverride])activeDomain=domainOverride;else if(page!=='experiments')activeDomain=domainForPage(page);activePage=page;if(page==='experiments')syncExperimentDomain();syncWorkspaceTabFromPage(page);if(WORKSPACE_PANES[page])clearWorkspacePaneVisibility(page);qa('.page').forEach(x=>x.classList.remove('active'));section.classList.add('active');const [e,t]=pageName(page);setText('pageEyebrow',e);setText('pageTitle',t);renderContextNav();$('sidebar').classList.remove('open');if(page==='navigation'){loadMapImage();loadCostmapImage('global');loadCostmapImage('local');drawMap()}if(page==='map-editor'){loadMapImage();loadCostmapImage('global');loadCostmapImage('local');window.mapEditorActivate?.()}queueRender();if(syncHmi&&webToHmiPage[page]&&obj('server').read_only!==true)post('/api/hmi/page',{page:webToHmiPage[page]},true)}
async function capturePerceptionEvidence(){
  const label=$('perceptionEvidenceLabel')?.value?.trim()||'commissioning',b=$('perceptionEvidenceCapture');if(b)b.disabled=true;setText('perceptionEvidenceState','SAVING');
  try{const r=await writeRequest('/api/perception/evidence',{label}),j=await r.json();setText('perceptionEvidenceResult',j.ok?pretty(j.evidence):j.message||'Capture failed');setText('perceptionEvidenceState',j.ok?'SAVED':'ERROR');if(!r.ok)toast(j.message||'Evidence capture gagal',true);else toast('Perception evidence tersimpan')}
  catch(e){setText('perceptionEvidenceState','ERROR');setText('perceptionEvidenceResult',String(e));toast('Evidence capture gagal: '+e.message,true)}finally{if(b)b.disabled=false}
}
function switchDomain(domain,syncHmi=true){if(!DOMAIN_MENU[domain])return;activeDomain=domain;const exp=DOMAIN_MENU[domain].exp;if(exp)currentExp=exp;const page=DOMAIN_MENU[domain].defaultPage;activatePage(page,false,domain);if(WORKSPACE_PANES[page])clearWorkspacePaneVisibility(page);if(syncHmi&&obj('server').read_only!==true&&webToHmiPage[page])post('/api/hmi/page',{page:webToHmiPage[page]},true)}
qa('.top-domain').forEach(b=>b.onclick=()=>switchDomain(b.dataset.domain,true));
$('menuButton').onclick=()=>$('sidebar').classList.toggle('open'); $('sidebarBackdrop').onclick=()=>$('sidebar').classList.remove('open'); document.addEventListener('keydown',e=>{if(e.key==='Escape')$('sidebar').classList.remove('open')});
function setSidebarCollapsed(collapsed,persist=true){const c=!!collapsed;document.body.classList.toggle('sidebar-collapsed',c);const btn=$('sidebarCollapseBtn'),mark=$('sidebarBrandMark');if(btn){btn.textContent=c?'›':'‹';btn.setAttribute('aria-label',c?'Buka sidebar':'Minimize sidebar')}if(mark){mark.setAttribute('aria-expanded',String(!c));mark.setAttribute('aria-label',c?'Buka sidebar':'ADV Control');mark.title=c?'Buka sidebar':'ADV Control'}if(persist)localStorage.setItem('adv-sidebar',c?'collapsed':'expanded')}
$('sidebarCollapseBtn').onclick=()=>setSidebarCollapsed(!document.body.classList.contains('sidebar-collapsed'));
$('sidebarBrandMark').onclick=()=>{if(document.body.classList.contains('sidebar-collapsed'))setSidebarCollapsed(false)};
$('sidebarBrandMark').onkeydown=e=>{if(document.body.classList.contains('sidebar-collapsed')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setSidebarCollapsed(false)}};
setSidebarCollapsed(localStorage.getItem('adv-sidebar')==='collapsed',false);
$('themeButton').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('adv-theme',document.body.classList.contains('light')?'light':'dark');drawMap()}; if(localStorage.getItem('adv-theme')==='light')document.body.classList.add('light');setupWorkspacePanes();for(const page of Object.keys(WORKSPACE_PANES))clearWorkspacePaneVisibility(page);renderContextNav();
if($('escOpenTuning'))$('escOpenTuning').onclick=()=>{activeDomain='esc';currentExp='steering';activatePage('experiments',false,'esc')};
if($('perceptionEvidenceCapture'))$('perceptionEvidenceCapture').onclick=capturePerceptionEvidence;if($('perceptionEvidenceOpenCamera'))$('perceptionEvidenceOpenCamera').onclick=()=>{activeDomain='perception';activateWorkspaceTab('live')};
function toast(msg,bad=false){const e=document.createElement('div');e.className='toast'+(bad?' bad':'');e.textContent=msg;$('toastStack').append(e);setTimeout(()=>e.remove(),4200)}
const dialogReturnFocus=new WeakMap();
function dialogFocusables(root){return qa('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex]:not([tabindex="-1"])',root).filter(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0})}
function setDialogBackgroundInert(on){const app=q('.app-shell');if(app)app.inert=!!on}
function openDialogFocus(root,preferred){if(!root)return;if(!dialogReturnFocus.has(root)&&document.activeElement instanceof HTMLElement)dialogReturnFocus.set(root,document.activeElement);setDialogBackgroundInert(true);requestAnimationFrame(()=>{const target=preferred||dialogFocusables(root)[0]||root;target?.focus?.()})}
function restoreDialogFocus(root){const prev=dialogReturnFocus.get(root);dialogReturnFocus.delete(root);if(!activeManagedDialog())setDialogBackgroundInert(false);if(prev?.isConnected&&!prev.closest('[hidden]'))prev.focus({preventScroll:true})}
function activeManagedDialog(){const modal=q('#confirmModal.show .modal');if(modal)return modal;const diff=$('configDiffDrawer');if(diff&&!diff.hidden)return diff;const help=$('helpDrawer');if(help&&!help.hidden)return help;return null}
function closeConfirmModal(){const root=q('#confirmModal .modal');$('confirmModal').classList.remove('show');confirmAction=null;restoreDialogFocus(root)}
let confirmAction=null;function confirmModal(title,text,fn){setText('confirmTitle',title);setText('confirmText',text);confirmAction=fn;$('confirmModal').classList.add('show');openDialogFocus(q('#confirmModal .modal'),$('confirmNo'))}$('confirmNo').onclick=closeConfirmModal;$('confirmYes').onclick=()=>{const fn=confirmAction,root=q('#confirmModal .modal');$('confirmModal').classList.remove('show');confirmAction=null;restoreDialogFocus(root);if(fn)fn()};
const API_REQUEST_KIND=Object.freeze({READ:'READ',WRITE_METADATA:'WRITE_METADATA',WRITE_CONFIG:'WRITE_CONFIG',MOTION_COMMAND:'MOTION_COMMAND'});
const API_DEFAULT_TIMEOUT_MS=5000;
function classifyApiRequest(url,method='GET'){
  const m=String(method||'GET').toUpperCase(),u=String(url||'');if(m==='GET'||m==='HEAD')return API_REQUEST_KIND.READ;
  if(/\/api\/(?:navigation\/(?:goal|cancel)|localization\/(?:initial-pose|reset-calibration)|experiment\/trial\/motion|hmi\/control|esc\/vesc\/command)/.test(u))return API_REQUEST_KIND.MOTION_COMMAND;
  if(/\/api\/(?:config\/(?:validate|apply|proposal)|imu\/calibration\/proposal|commissioning\/qualification)/.test(u))return API_REQUEST_KIND.WRITE_CONFIG;
  return API_REQUEST_KIND.WRITE_METADATA;
}
async function fetchWithTimeout(url,options={},timeoutMs=API_DEFAULT_TIMEOUT_MS){
  const controller=new AbortController(),ms=Math.max(250,+timeoutMs||API_DEFAULT_TIMEOUT_MS);let timedOut=false;
  const timer=setTimeout(()=>{timedOut=true;controller.abort()},ms);
  try{return await fetch(url,{...options,signal:controller.signal})}
  catch(e){e.agvCode=timedOut?'REQUEST_TIMEOUT':'NETWORK_ERROR';e.agvTimeoutMs=ms;throw e}
  finally{clearTimeout(timer)}
}
window.AGVFetchWithTimeout=fetchWithTimeout;
function jsonResponseFacade(ok,status,statusText,data,headers=null,requestKind=API_REQUEST_KIND.READ){return {ok,status,statusText,headers,requestKind,json:async()=>data}}
function writeLockState(){if(replayMode)return {replay_locked:true,code:'REPLAY_LOCKED',message:'REPLAY MODE aktif: semua command/write diblokir.'};if(obj('server').read_only===true)return {read_only:true,code:'READ_ONLY',message:'Server read-only: semua command/write diblokir.'};return null}
function apiFailure(code,message,{status=0,statusText='Request Error',headers=null,kind=API_REQUEST_KIND.READ,extra={}}={}){return jsonResponseFacade(false,status,statusText,{ok:false,code,message,request_kind:kind,...extra},headers,kind)}
async function apiRequest(url,{method='GET',body,timeoutMs=API_DEFAULT_TIMEOUT_MS,cache='no-store',kind,headers={},expectJson=true}={}){
  const verb=String(method||'GET').toUpperCase(),requestKind=kind||classifyApiRequest(url,verb),isWrite=!['GET','HEAD'].includes(verb);
  if(isWrite){const lock=writeLockState();if(lock)return apiFailure(lock.code,lock.message,{status:423,statusText:'Locked',kind:requestKind,extra:lock})}
  const opts={method:verb,cache,headers:{...headers}};if(body!==undefined){opts.headers['Content-Type']=opts.headers['Content-Type']||'application/json';opts.body=typeof body==='string'?body:JSON.stringify(body)}
  let r;try{r=await fetchWithTimeout(url,opts,timeoutMs)}catch(e){const code=e.agvCode||'NETWORK_ERROR',msg=code==='REQUEST_TIMEOUT'?`Request timeout ${e.agvTimeoutMs||timeoutMs} ms (${url})`:`Network request gagal (${url}): ${e.message}`;return apiFailure(code,msg,{kind:requestKind,extra:{network_error:code==='NETWORK_ERROR',timeout:code==='REQUEST_TIMEOUT',timeout_ms:e.agvTimeoutMs||timeoutMs}})}
  if(!expectJson)return r;
  let text='';try{text=await r.text()}catch(e){return apiFailure('RESPONSE_READ_ERROR',`Response tidak dapat dibaca (${url}): ${e.message}`,{status:r.status||0,statusText:r.statusText||'Read Error',headers:r.headers,kind:requestKind,extra:{response_read_error:true}})}
  let data={};if(text){try{data=JSON.parse(text)}catch(_){return apiFailure('MALFORMED_JSON',`Malformed JSON response (${url})`,{status:r.status||502,statusText:'Malformed JSON',headers:r.headers,kind:requestKind,extra:{malformed_json:true}})}}
  if(data!==null&&typeof data!=='object')return apiFailure('INVALID_JSON_SHAPE',`JSON response harus object/array (${url})`,{status:r.status||502,statusText:'Invalid JSON Shape',headers:r.headers,kind:requestKind});
  if(!r.ok&&data&&typeof data==='object'&&!Array.isArray(data)&&!data.code)data.code=`HTTP_${r.status}`;
  return jsonResponseFacade(r.ok,r.status,r.statusText,data,r.headers,requestKind)
}
function readRequest(url,opts={}){return apiRequest(url,{...opts,method:'GET',kind:API_REQUEST_KIND.READ})}
function writeRequest(url,body={},opts={}){return apiRequest(url,{...opts,method:'POST',body,kind:opts.kind||classifyApiRequest(url,'POST')})}
async function post(url,body={},silent=false){const r=await writeRequest(url,body),j=await r.json();if(!silent||!r.ok)toast(j.message||(`${r.status||'NETWORK'} ${r.statusText||'Request failed'}`),!r.ok);return j}
function trackChannelTiming(ups){const now=Date.now(),windowMs=10000;for(const [k,rawT] of Object.entries(ups||{})){const t=+rawT;if(!Number.isFinite(t))continue;let m=channelTiming.get(k);if(!m)m={last:0,dts:[],missingEvents:[]};if(!Array.isArray(m.missingEvents))m.missingEvents=[];m.missingEvents=m.missingEvents.filter(x=>now-x.at<=windowMs);if(m.last>0&&t>m.last){const dt=t-m.last,expected=CHANNEL_REGISTRY[k]?.expectedHz,nominal=expected>0?1000/expected:0,resetGap=nominal>0?Math.max(1000,nominal*10):1000;if(dt>0&&dt<=resetGap){m.dts.push(dt);while(m.dts.length>80)m.dts.shift();if(nominal>0&&dt>nominal*1.65){const count=Math.max(0,Math.round(dt/nominal)-1);if(count)m.missingEvents.push({at:now,count})}}else if(dt>resetGap){m.dts=[];m.missingEvents=[]}}if(t>m.last)m.last=t;channelTiming.set(k,m)}}
function channelDt(k){const a=channelTiming.get(k)?.dts||[];return a.length?a[a.length-1]/1000:undefined}
function channelRate(k){const a=channelTiming.get(k)?.dts||[];if(!a.length)return undefined;const recent=a.slice(-30),mean=recent.reduce((x,y)=>x+y,0)/recent.length;return mean>0?1000/mean:undefined}
function channelJitterMs(k){const a=(channelTiming.get(k)?.dts||[]).slice(-40);if(a.length<2)return undefined;const mean=a.reduce((x,y)=>x+y,0)/a.length;return Math.sqrt(a.reduce((n,v)=>n+(v-mean)**2,0)/a.length)}
function channelMissing(k){const m=channelTiming.get(k);if(!m||!Array.isArray(m.missingEvents))return 0;const now=Date.now();m.missingEvents=m.missingEvents.filter(x=>now-x.at<=10000);return m.missingEvents.reduce((sum,x)=>sum+(+x.count||0),0)}
function channelHealth(k){const meta=CHANNEL_REGISTRY[k]||{},a=age(k)*1000,r=channelRate(k),stale=meta.staleMs||1000;if(a<=stale&&(!meta.expectedHz||!Number.isFinite(r)||r>=meta.expectedHz*.55))return'LIVE';if(a<=stale*3)return'DEGRADED';return'STALE'}
function mergeSticky(prev,next){if(!prev||typeof prev!=='object'||Array.isArray(prev)||!next||typeof next!=='object'||Array.isArray(next))return next;const out={...prev};for(const [k,v] of Object.entries(next))out[k]=(v&&typeof v==='object'&&!Array.isArray(v)&&prev[k]&&typeof prev[k]==='object'&&!Array.isArray(prev[k]))?mergeSticky(prev[k],v):v;return out}
function queueRender(force=false){if(renderQueued)return;if(document.hidden&&!force)return;renderQueued=true;const delay=force?0:Math.max(0,activeRenderMs()-(performance.now()-lastRenderAt)),run=()=>requestAnimationFrame(()=>{renderQueued=false;if(document.hidden&&!force)return;lastRenderAt=performance.now();render()});delay>1?setTimeout(run,delay):run()}
function merge(delta){if(!delta||typeof delta!=='object')return;const ups=delta.__updated||{};Object.entries(delta).forEach(([k,v])=>{if(k.startsWith('__'))return;state[k]=STICKY_STREAMS.has(k)?mergeSticky(state[k],v):v});if(delta.map_meta&&['navigation','map-editor'].includes(activePage)&&typeof loadMapImage==='function')setTimeout(()=>loadMapImage(),0);if(delta.global_costmap_meta&&['navigation','map-editor'].includes(activePage)&&typeof loadCostmapImage==='function')setTimeout(()=>loadCostmapImage('global'),0);if(delta.local_costmap_meta&&['navigation','map-editor'].includes(activePage)&&typeof loadCostmapImage==='function')setTimeout(()=>loadCostmapImage('local'),0);if(delta.nav_path&&pendingPlanGoalAtMs>0){lastPlanningLatencyMs=Math.max(0,Date.now()-pendingPlanGoalAtMs);pendingPlanGoalAtMs=0;if(state.nav_path&&typeof state.nav_path==='object')state.nav_path.planning_latency_ms=lastPlanningLatencyMs}else if(delta.nav_path&&Number.isFinite(lastPlanningLatencyMs)&&state.nav_path&&typeof state.nav_path==='object')state.nav_path.planning_latency_ms=lastPlanningLatencyMs;trackChannelTiming(ups);Object.assign(updated,ups);if(delta.__server_time_ms)serverDelta=Date.now()-delta.__server_time_ms;trackRuntimeEvents();window.captureVescToolState?.();window.captureReport41TimedDelta?.(delta,ups);if(Array.isArray(delta.__imu_samples))delta.__imu_samples.forEach(s=>window.captureImuHeadingLinearitySample?.(s));else if(delta.imu)window.captureImuHeadingLinearitySample?.(delta.imu);if(activePage==='experiments')captureLabTelemetry?.();queueRender()}
let sseLastDataAt=0,sseFallbackBusy=false;
async function fullState(force=false){if(replayMode&&!force)return false;try{const r=await readRequest('/api/state',{timeoutMs:2500}),j=await r.json();if(!r.ok)throw new Error(j.message||`HTTP ${r.status}`);merge(j);return true}catch(e){return false}}
async function requestSseResync(){if(sseResyncBusy)return;sseResyncBusy=true;const ok=await fullState();if(ok)sseResyncCount++;sseResyncBusy=false}
function ingestSseEvent(e,isSnapshot=false){sseLastDataAt=Date.now();try{const d=JSON.parse(e.data),seq=Number(d.__event_seq);if(Number.isFinite(seq)){if(!isSnapshot&&Number.isFinite(sseLastSeq)&&seq!==sseLastSeq+1){sseGapCount+=Math.max(1,seq-sseLastSeq-1);requestSseResync()}sseLastSeq=seq}merge(d)}catch(_){sseGapCount++;requestSseResync()}}
function markSseSnapshot(e){ingestSseEvent(e,true)}
function markSseData(e){ingestSseEvent(e,false)}
function setRealtimeUi(mode){const live=mode==='sse',poll=mode==='poll';setText('sseLabel',live?'Live stream':poll?'Polling live':'Offline');$('sseDot').style.background=live?'var(--green)':poll?'var(--amber)':'var(--red)';setText('diagSse',live?'CONNECTED':poll?'POLLING':'OFFLINE');setText('footerStatus',live?'ROS2 realtime telemetry connected':poll?'ROS2 telemetry via robust polling fallback':'ROS2 telemetry disconnected')}
function connectSse(){if(sse)sse.close();sseLastDataAt=0;sseLastSeq=null;sse=new EventSource('/api/events');sse.onopen=()=>{sseLastDataAt=Date.now();setRealtimeUi('sse')};sse.addEventListener('snapshot',markSseSnapshot);sse.onmessage=markSseData;sse.onerror=()=>setRealtimeUi('poll')}
async function realtimeFallbackTick(){if(replayMode)return;const stale=!sse||sse.readyState!==EventSource.OPEN||!sseLastDataAt||Date.now()-sseLastDataAt>2500;if(!stale)return;if(sseFallbackBusy)return;sseFallbackBusy=true;const ok=await fullState();sseFallbackBusy=false;if(ok&&(!sse||sse.readyState!==EventSource.OPEN))setRealtimeUi('poll');else if(!ok&&(!sse||sse.readyState!==EventSource.OPEN))setRealtimeUi('offline')}
function healthFromConnected(key,dataKey='',sec=3){if(!bool(raw(key)))return'bad';return !dataKey||channelFresh(dataKey,sec)?'ok':'warn'}
function renderDataHealth(){const body=$('dataHealthRows');if(!body)return;let live=0,degraded=0,stale=0;body.innerHTML=Object.entries(CHANNEL_REGISTRY).map(([k,m])=>{const h=channelHealth(k),r=channelRate(k),a=age(k),j=channelJitterMs(k),miss=channelMissing(k);if(h==='LIVE')live++;else if(h==='DEGRADED')degraded++;else stale++;return `<tr class="health-${h.toLowerCase()}"><td><b>${escapeHtml(m.label)}</b><small>${escapeHtml(k)}</small></td><td>${Number.isFinite(r)?r.toFixed(1):'--'} Hz</td><td>${Number.isFinite(a)?(a*1000).toFixed(0):'--'} ms</td><td>${Number.isFinite(j)?j.toFixed(1):'--'} ms</td><td>${miss}</td><td><span class="health-state health-state-${h.toLowerCase()}">${h}</span></td></tr>`}).join('');const summary=$('dataHealthSummary');if(summary){summary.textContent=stale?`${stale} STALE`:degraded?`${degraded} DEGRADED`:`${live} LIVE`;summary.className='status-chip '+(stale?'bad':degraded?'waiting':'')}setText('sseIntegritySummary',`SSE seq ${Number.isFinite(sseLastSeq)?sseLastSeq:'--'} • gaps ${sseGapCount} • resync ${sseResyncCount}`)}
function authorityKey(){const tool=obj('vesc_tool_status'),mux=String(getPath(obj('esc_mux'),'raw')||getPath(obj('nav_cmd_mux'),'raw')||'IDLE').toUpperCase();if(bool(raw('system.estop'))||mux.includes('E_STOP')||mux.includes('ESTOP'))return'estop';if(tool.python_tcp_client===true||tool.python_tcp_armed===true)return'python';if(tool.tcp_client===true||tool.tcp_armed===true)return'vesc';if(bool(raw('vesc_maintenance_active'))||/MANUAL|TELEOP|HMI|WEB|JOYSTICK/.test(mux))return'manual';if(mux.includes('PERCEPTION'))return'perception';if(/NAV2|AUTONOMY/.test(mux))return'nav2';return'idle'}
function setPriorityStatus(id,value,state='wait',detail=''){const el=$(id);if(!el)return;el.textContent=value;const card=el.closest('.operator-priority-item');if(card)card.dataset.state=state;const d=$(id+'Detail');if(d&&detail)d.textContent=detail}
function renderAuthority(){const key=authorityKey(),tool=obj('vesc_tool_status'),mux=getPath(obj('esc_mux'),'raw')||getPath(obj('nav_cmd_mux'),'raw')||'IDLE';qa('[data-authority]').forEach(e=>e.classList.toggle('active',e.dataset.authority===key));const chip=$('authorityChip');if(chip){chip.textContent=key.toUpperCase();chip.className='status-chip '+(key==='estop'?'bad':key==='idle'?'waiting':'')}setText('authoritySource',String(mux));setText('authorityMotion',bool(raw('system.motion_ready'))?'OPEN':'FAIL-CLOSED');setText('authorityEscOwner',tool.owner||tool.mode||'--')}
function renderOverview(){
  const now=performance.now();
  renderHeadingEkfSummary('overview');
  const gn=healthFromConnected('connected.gnss','gnss_fix',2),im=healthFromConnected('connected.imu','imu',2),ca=healthFromConnected('connected.camera','camera_frame',4),es=bool(raw('connected.esc_feedback'))?'ok':(bool(raw('connected.esc_ready'))?'warn':'bad'),loc=bool(raw('system.motion_ready'))?'ok':(channelFresh('localization_state',5)?'warn':'bad'),nv=bool(raw('system.nav2_ready'))?'ok':(channelFresh('system.nav2_ready',5)?'warn':'bad'),hm=bool(raw('connected.hmi'))?'ok':'bad';
  const states=[gn,im,ca,es,hm,loc,nv],score=Math.round(states.reduce((a,x)=>a+(x==='ok'?1:x==='warn'?.5:0),0)/states.length*100),motion=bool(raw('system.motion_ready')),auth=authorityKey(),safetyBad=bool(raw('system.estop'))||bool(raw('perception_emergency'));
  setPriorityStatus('priorityMotion',motion?'READY':'FAIL-CLOSED',motion?'ok':'bad',`readiness ${score}%`);setPriorityStatus('priorityAuthority',auth.toUpperCase(),auth==='estop'?'bad':(auth==='idle'||auth==='manual')?'warn':'ok',String(getPath(obj('esc_mux'),'raw')||'IDLE'));setPriorityStatus('priorityLocalization',loc==='ok'?'READY':loc==='warn'?'DEGRADED':'NOT READY',loc,textish(obj('localization_state').state||obj('localization_state').raw||'waiting'));setPriorityStatus('priorityEsc',es==='ok'?'FEEDBACK OK':es==='warn'?'GATEWAY ONLY':'OFFLINE',es,bool(raw('connected.esc_feedback'))?'fresh feedback':'waiting feedback');setPriorityStatus('priorityPerception',ca==='ok'?'HEALTHY':ca==='warn'?'DEGRADED':'OFFLINE',ca,obj('camera_frame').source||'camera');setPriorityStatus('prioritySafety',safetyBad?'BLOCKED':motion?'CLEAR':'GUARDED',safetyBad?'bad':motion?'ok':'warn',`E-stop ${bool(raw('system.estop'))?'ACTIVE':'clear'} • perception ${bool(raw('perception_emergency'))?'EMERGENCY':'clear'}`);
  {setText('readinessPct',score+'%');$('readinessRing').style.setProperty('--pct',score);setText('readinessTitle',motion?'Vehicle motion-ready':score>=70?'Hardware online, gates pending':'System commissioning / offline');setText('readinessDetail',motion?'Localization, Nav2 and actuator safety gates report ready.':'Check cards and active conditions below. Motion stays fail-closed until required calibration and runtime gates pass.');setText('overallChip',motion?'MOTION READY':'FAIL-CLOSED');$('overallChip').className='status-chip '+(motion?'':'waiting');const eg=obj('ekf_global'),imu=obj('imu'),hnav=obj('hmi_navigation'),gstate=getPath(obj('goal_state'),'state')||hnav.state||'IDLE',gtarget=hnav.target&&hnav.target!=='NONE'?` • ${hnav.target}`:'';setText('overviewSpeed',fmt(getPath(obj('esc_odom'),'v')??getPath(obj('ekf_local'),'v')));setText('overviewSteer',fmt(deg(raw('esc_steer_actual')),1));setText('overviewYaw',fmt(deg(getPath(eg,'yaw')??getPath(imu,'yaw_rad')),1));setText('goalStateBig',gstate+gtarget);setText('activeSourceBig','ACTUATOR: '+(getPath(obj('esc_mux'),'raw')||'--'));setText('lastUpdate',new Date().toLocaleTimeString('id-ID'))}
  if(now-lastOverviewHealthAt>=500||!lastOverviewHealthAt){lastOverviewHealthAt=now;const joy=bool(raw('connected.joystick'))?'ok':'bad',js=obj('joystick_status');healthCard('gnss',gn,getPath(obj('gnss_quality'),'sat')!=null?`${fmt(getPath(obj('gnss_quality'),'sat'),0)} sat • hAcc ${fmt(getPath(obj('gnss_quality'),'hacc_m'))}m`:'NEO-3 via F411 CDC');healthCard('imu',im,'Yahboom IMU • CP2102');healthCard('camera',ca,obj('camera_frame').source||'Astra Pro');healthCard('esc',es,bool(raw('connected.esc_feedback'))?'USB→F103 • ACK fresh':'USB→F103 • waiting ACK');healthCard('localization',loc,textish(obj('localization_state').state||obj('localization_state').raw||'waiting'));healthCard('nav2',nv,bool(raw('system.nav2_ready'))?'planner/controller ready':'waiting gates');healthCard('hmi',hm,`${raw('hmi_page')||'--'} • ${raw('hmi_mode')||'--'}`);healthCard('joystick',joy,joy==='ok'?`${js.state||'CONNECTED'} • telemetry only`:'DISCONNECTED • tidak menutup gate');renderDataHealth()}
  {const ct=obj('cmd_teleop'),cp=obj('cmd_pre_smoother'),cs=obj('cmd_autonomy_integrated'),cf=obj('cmd_final'),caa=obj('cmd_actuator'),mux=getPath(obj('nav_cmd_mux'),'raw')||'IDLE',input=String(mux).startsWith('TELEOP')?ct:cs;setText('pipeInputLabel',`Selected input • ${mux}`);setText('pipeNav',fmt(input.linear_x));setText('pipeSafety',fmt(cp.linear_x));setText('pipeFinal',fmt(cf.linear_x));setText('pipeActuator',fmt(caa.linear_x));history.push({t:Date.now(),nav:+input.linear_x||0,final:+cf.linear_x||0,actual:+raw('esc_drive_actual')||0});while(history.length>180)history.shift();drawSpark();renderAuthority()}
  {renderAlerts();renderEventTimeline()}
}
function addRuntimeEvent(kind,value,severity='info',meta={}){
  const atMs=Date.now(),origin=recordStartedMs||chartEpochMs,analysisTime=Math.max(0,(atMs-origin)/1000),input={timestamp_ms:atMs,severity,domain:meta.domain||'system',layer:meta.layer||'runtime',source:meta.source||'ros_web',code:meta.code||String(kind).toUpperCase().replace(/[^A-Z0-9]+/g,'_'),summary:kind,state:value,related_channels:meta.related_channels||[],related_evidence:meta.related_evidence||[],analysis_time_s:analysisTime},e=window.AGVDiagnostics?.normalizeEvent(input)||{...input,atMs,kind,value:String(value),text:`${kind}: ${value}`,severity_css:severity==='danger'?'danger':severity==='warn'?'warn':'info'};
  eventLog.push(e);while(eventLog.length>240)eventLog.shift();if(activePage==='overview')renderEventTimeline()
}
function watchRuntimeEvent(key,value,label,severity='info',meta={}){const norm=String(value??'--');if(!eventLast.has(key)){eventLast.set(key,norm);return}if(eventLast.get(key)===norm)return;eventLast.set(key,norm);addRuntimeEvent(label,norm,severity,meta)}
function trackRuntimeEvents(){
  const tool=obj('vesc_tool_status');
  watchRuntimeEvent('goal',getPath(obj('goal_state'),'state')||'IDLE','GOAL','info',{domain:'navigation',layer:'mission',source:'goal_state',related_channels:['goal_state']});
  watchRuntimeEvent('esc_mux',getPath(obj('esc_mux'),'raw')||'IDLE','ESC AUTHORITY','info',{domain:'esc',layer:'authority',source:'esc_mux',related_channels:['esc_mux']});
  watchRuntimeEvent('nav_mux',getPath(obj('nav_cmd_mux'),'raw')||'IDLE','NAV MUX','info',{domain:'navigation',layer:'control',source:'nav_cmd_mux',related_channels:['nav_cmd_mux','cmd_final']});
  watchRuntimeEvent('motion',bool(raw('system.motion_ready'))?'OPEN':'LOCKED','MOTION GATE',bool(raw('system.motion_ready'))?'info':'warn',{domain:'system',layer:'safety',source:'system.motion_ready',related_channels:['system.motion_ready']});
  watchRuntimeEvent('estop',bool(raw('system.estop'))?'ACTIVE':'CLEAR','E-STOP',bool(raw('system.estop'))?'danger':'info',{domain:'system',layer:'hardware_safety',source:'system.estop',related_channels:['system.estop']});
  watchRuntimeEvent('perception_emergency',bool(raw('perception_emergency'))?'ACTIVE':'CLEAR','PERCEPTION EMERGENCY',bool(raw('perception_emergency'))?'danger':'info',{domain:'perception',layer:'safety',source:'perception_emergency',related_channels:['perception_emergency','trajectory_safety_state']});
  watchRuntimeEvent('gnss',bool(raw('connected.gnss'))?'CONNECTED':'OFFLINE','GNSS',bool(raw('connected.gnss'))?'info':'warn',{domain:'navigation',layer:'sensor',source:'connected.gnss',related_channels:['connected.gnss','gnss_quality']});
  watchRuntimeEvent('hmi',bool(raw('connected.hmi'))?'CONNECTED':'OFFLINE','F4 HMI',bool(raw('connected.hmi'))?'info':'warn',{domain:'system',layer:'transport',source:'connected.hmi',related_channels:['connected.hmi','hmi_page','hmi_mode']});
  watchRuntimeEvent('vesc_transport',bool(raw('connected.vesc_transport'))?'CONNECTED':'OFFLINE','USB-F103 TRANSPORT',bool(raw('connected.vesc_transport'))?'info':'danger',{domain:'esc',layer:'transport',source:'vesc_transport_status',related_channels:['connected.vesc_transport','vesc_transport_status','vesc_transport_error']});
  watchRuntimeEvent('vesc_owner',tool.owner||tool.mode||'--','VESC OWNER','info',{domain:'esc',layer:'authority',source:'vesc_tool_status',related_channels:['vesc_tool_status']})
}
function renderEventTimeline(){
  const box=$('eventTimeline');if(!box)return;const rows=eventLog.slice(-40).reverse();
  box.innerHTML=rows.length?rows.map(e=>{const idx=eventLog.indexOf(e),sev=String(e.severity||'INFO'),css=e.severity_css||(sev==='CRITICAL'||sev==='ERROR'?'danger':sev==='WARNING'?'warn':'info');return `<div class="event-row event-${css}" role="button" tabindex="0" data-event-index="${idx}" title="${escapeHtml(`${e.domain||'system'} / ${e.layer||'runtime'} / ${e.source||'--'}`)}"><time>${new Date(e.timestamp_ms||e.atMs).toLocaleTimeString('id-ID',{hour12:false})}</time><b>${escapeHtml(e.summary||e.kind||e.code)}</b><span>${escapeHtml(e.state??e.value??'')} <small>${escapeHtml(sev)}</small></span></div>`}).join(''):'<div class="empty-state">No runtime events yet.</div>';
  const open=row=>{const e=eventLog[+row.dataset.eventIndex];if(!e)return;window.analysisSession?.selectEvent(e);row.classList.add('selected');setTimeout(()=>row.classList.remove('selected'),900)};
  qa('[data-event-index]',box).forEach(row=>{row.onclick=()=>open(row);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(row)}}})
}
function renderAlerts(){const a=[];if(bool(raw('system.estop')))a.push(['danger','Emergency stop ACTIVE']);if(bool(raw('perception_emergency')))a.push(['danger','Perception emergency stop ACTIVE']);if(!bool(raw('connected.esc_feedback')))a.push(['danger','ESC ACK belum fresh — motor command tidak dianggap ready']);if(!bool(raw('connected.gnss')))a.push(['warn','GNSS belum connected']);if(!bool(raw('connected.imu')))a.push(['warn','IMU belum connected']);if(!bool(raw('system.motion_ready')))a.push(['warn','Motion gate masih tertutup']);if(bool(raw('system.motion_ready'))&&bool(raw('connected.esc_feedback')))a.push(['ok','Core motion chain ready']);setText('alertCount',a.filter(x=>x[0]!=='ok').length);$('alerts').innerHTML=a.length?a.map(x=>`<div class="alert-item ${x[0]}">${escapeHtml(x[1])}</div>`).join(''):'<div class="empty-state">Tidak ada kondisi aktif.</div>'}
function drawSpark(){const c=$('speedSpark'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const css=getComputedStyle(document.body);ctx.strokeStyle=css.getPropertyValue('--border2');ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();if(history.length<2)return;const max=Math.max(1,...history.flatMap(x=>[Math.abs(x.nav),Math.abs(x.final),Math.abs(x.actual)]));[['nav','--blue'],['final','--green'],['actual','--cyan']].forEach(([key,col])=>{ctx.strokeStyle=css.getPropertyValue(col);ctx.lineWidth=2;ctx.beginPath();history.forEach((p,i)=>{const x=i/(history.length-1)*w,y=h/2-(p[key]/max)*(h*.38);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()})}
